// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package borrower

import (
	"context"

	"github.com/BagusAK95/amarta_test/internal/domain/borrower"
	"github.com/BagusAK95/amarta_test/internal/domain/common/repository"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
	"gorm.io/gorm"
)

// NewMockIBorrowerRepository creates a new instance of MockIBorrowerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIBorrowerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIBorrowerRepository {
	mock := &MockIBorrowerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIBorrowerRepository is an autogenerated mock type for the IBorrowerRepository type
type MockIBorrowerRepository struct {
	mock.Mock
}

type MockIBorrowerRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIBorrowerRepository) EXPECT() *MockIBorrowerRepository_Expecter {
	return &MockIBorrowerRepository_Expecter{mock: &_m.Mock}
}

// BeginTransaction provides a mock function for the type MockIBorrowerRepository
func (_mock *MockIBorrowerRepository) BeginTransaction(ctx context.Context) *gorm.DB {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for BeginTransaction")
	}

	var r0 *gorm.DB
	if returnFunc, ok := ret.Get(0).(func(context.Context) *gorm.DB); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}
	return r0
}

// MockIBorrowerRepository_BeginTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginTransaction'
type MockIBorrowerRepository_BeginTransaction_Call struct {
	*mock.Call
}

// BeginTransaction is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIBorrowerRepository_Expecter) BeginTransaction(ctx interface{}) *MockIBorrowerRepository_BeginTransaction_Call {
	return &MockIBorrowerRepository_BeginTransaction_Call{Call: _e.mock.On("BeginTransaction", ctx)}
}

func (_c *MockIBorrowerRepository_BeginTransaction_Call) Run(run func(ctx context.Context)) *MockIBorrowerRepository_BeginTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIBorrowerRepository_BeginTransaction_Call) Return(dB *gorm.DB) *MockIBorrowerRepository_BeginTransaction_Call {
	_c.Call.Return(dB)
	return _c
}

func (_c *MockIBorrowerRepository_BeginTransaction_Call) RunAndReturn(run func(ctx context.Context) *gorm.DB) *MockIBorrowerRepository_BeginTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// Commit provides a mock function for the type MockIBorrowerRepository
func (_mock *MockIBorrowerRepository) Commit(trx *gorm.DB) *gorm.DB {
	ret := _mock.Called(trx)

	if len(ret) == 0 {
		panic("no return value specified for Commit")
	}

	var r0 *gorm.DB
	if returnFunc, ok := ret.Get(0).(func(*gorm.DB) *gorm.DB); ok {
		r0 = returnFunc(trx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}
	return r0
}

// MockIBorrowerRepository_Commit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Commit'
type MockIBorrowerRepository_Commit_Call struct {
	*mock.Call
}

// Commit is a helper method to define mock.On call
//   - trx *gorm.DB
func (_e *MockIBorrowerRepository_Expecter) Commit(trx interface{}) *MockIBorrowerRepository_Commit_Call {
	return &MockIBorrowerRepository_Commit_Call{Call: _e.mock.On("Commit", trx)}
}

func (_c *MockIBorrowerRepository_Commit_Call) Run(run func(trx *gorm.DB)) *MockIBorrowerRepository_Commit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIBorrowerRepository_Commit_Call) Return(dB *gorm.DB) *MockIBorrowerRepository_Commit_Call {
	_c.Call.Return(dB)
	return _c
}

func (_c *MockIBorrowerRepository_Commit_Call) RunAndReturn(run func(trx *gorm.DB) *gorm.DB) *MockIBorrowerRepository_Commit_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockIBorrowerRepository
func (_mock *MockIBorrowerRepository) Create(ctx context.Context, model borrower.Borrower) (borrower.Borrower, error) {
	ret := _mock.Called(ctx, model)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 borrower.Borrower
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, borrower.Borrower) (borrower.Borrower, error)); ok {
		return returnFunc(ctx, model)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, borrower.Borrower) borrower.Borrower); ok {
		r0 = returnFunc(ctx, model)
	} else {
		r0 = ret.Get(0).(borrower.Borrower)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, borrower.Borrower) error); ok {
		r1 = returnFunc(ctx, model)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIBorrowerRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIBorrowerRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - model borrower.Borrower
func (_e *MockIBorrowerRepository_Expecter) Create(ctx interface{}, model interface{}) *MockIBorrowerRepository_Create_Call {
	return &MockIBorrowerRepository_Create_Call{Call: _e.mock.On("Create", ctx, model)}
}

func (_c *MockIBorrowerRepository_Create_Call) Run(run func(ctx context.Context, model borrower.Borrower)) *MockIBorrowerRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 borrower.Borrower
		if args[1] != nil {
			arg1 = args[1].(borrower.Borrower)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIBorrowerRepository_Create_Call) Return(borrower1 borrower.Borrower, err error) *MockIBorrowerRepository_Create_Call {
	_c.Call.Return(borrower1, err)
	return _c
}

func (_c *MockIBorrowerRepository_Create_Call) RunAndReturn(run func(ctx context.Context, model borrower.Borrower) (borrower.Borrower, error)) *MockIBorrowerRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateBulk provides a mock function for the type MockIBorrowerRepository
func (_mock *MockIBorrowerRepository) CreateBulk(ctx context.Context, models []borrower.Borrower) error {
	ret := _mock.Called(ctx, models)

	if len(ret) == 0 {
		panic("no return value specified for CreateBulk")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []borrower.Borrower) error); ok {
		r0 = returnFunc(ctx, models)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIBorrowerRepository_CreateBulk_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBulk'
type MockIBorrowerRepository_CreateBulk_Call struct {
	*mock.Call
}

// CreateBulk is a helper method to define mock.On call
//   - ctx context.Context
//   - models []borrower.Borrower
func (_e *MockIBorrowerRepository_Expecter) CreateBulk(ctx interface{}, models interface{}) *MockIBorrowerRepository_CreateBulk_Call {
	return &MockIBorrowerRepository_CreateBulk_Call{Call: _e.mock.On("CreateBulk", ctx, models)}
}

func (_c *MockIBorrowerRepository_CreateBulk_Call) Run(run func(ctx context.Context, models []borrower.Borrower)) *MockIBorrowerRepository_CreateBulk_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []borrower.Borrower
		if args[1] != nil {
			arg1 = args[1].([]borrower.Borrower)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIBorrowerRepository_CreateBulk_Call) Return(err error) *MockIBorrowerRepository_CreateBulk_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIBorrowerRepository_CreateBulk_Call) RunAndReturn(run func(ctx context.Context, models []borrower.Borrower) error) *MockIBorrowerRepository_CreateBulk_Call {
	_c.Call.Return(run)
	return _c
}

// CreateBulkAndReturnWithTx provides a mock function for the type MockIBorrowerRepository
func (_mock *MockIBorrowerRepository) CreateBulkAndReturnWithTx(ctx context.Context, models []borrower.Borrower, trx *gorm.DB) ([]borrower.Borrower, error) {
	ret := _mock.Called(ctx, models, trx)

	if len(ret) == 0 {
		panic("no return value specified for CreateBulkAndReturnWithTx")
	}

	var r0 []borrower.Borrower
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []borrower.Borrower, *gorm.DB) ([]borrower.Borrower, error)); ok {
		return returnFunc(ctx, models, trx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []borrower.Borrower, *gorm.DB) []borrower.Borrower); ok {
		r0 = returnFunc(ctx, models, trx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]borrower.Borrower)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []borrower.Borrower, *gorm.DB) error); ok {
		r1 = returnFunc(ctx, models, trx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIBorrowerRepository_CreateBulkAndReturnWithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBulkAndReturnWithTx'
type MockIBorrowerRepository_CreateBulkAndReturnWithTx_Call struct {
	*mock.Call
}

// CreateBulkAndReturnWithTx is a helper method to define mock.On call
//   - ctx context.Context
//   - models []borrower.Borrower
//   - trx *gorm.DB
func (_e *MockIBorrowerRepository_Expecter) CreateBulkAndReturnWithTx(ctx interface{}, models interface{}, trx interface{}) *MockIBorrowerRepository_CreateBulkAndReturnWithTx_Call {
	return &MockIBorrowerRepository_CreateBulkAndReturnWithTx_Call{Call: _e.mock.On("CreateBulkAndReturnWithTx", ctx, models, trx)}
}

func (_c *MockIBorrowerRepository_CreateBulkAndReturnWithTx_Call) Run(run func(ctx context.Context, models []borrower.Borrower, trx *gorm.DB)) *MockIBorrowerRepository_CreateBulkAndReturnWithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []borrower.Borrower
		if args[1] != nil {
			arg1 = args[1].([]borrower.Borrower)
		}
		var arg2 *gorm.DB
		if args[2] != nil {
			arg2 = args[2].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIBorrowerRepository_CreateBulkAndReturnWithTx_Call) Return(borrowers []borrower.Borrower, err error) *MockIBorrowerRepository_CreateBulkAndReturnWithTx_Call {
	_c.Call.Return(borrowers, err)
	return _c
}

func (_c *MockIBorrowerRepository_CreateBulkAndReturnWithTx_Call) RunAndReturn(run func(ctx context.Context, models []borrower.Borrower, trx *gorm.DB) ([]borrower.Borrower, error)) *MockIBorrowerRepository_CreateBulkAndReturnWithTx_Call {
	_c.Call.Return(run)
	return _c
}

// CreateBulkWithTx provides a mock function for the type MockIBorrowerRepository
func (_mock *MockIBorrowerRepository) CreateBulkWithTx(ctx context.Context, models []borrower.Borrower, trx *gorm.DB) error {
	ret := _mock.Called(ctx, models, trx)

	if len(ret) == 0 {
		panic("no return value specified for CreateBulkWithTx")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []borrower.Borrower, *gorm.DB) error); ok {
		r0 = returnFunc(ctx, models, trx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIBorrowerRepository_CreateBulkWithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBulkWithTx'
type MockIBorrowerRepository_CreateBulkWithTx_Call struct {
	*mock.Call
}

// CreateBulkWithTx is a helper method to define mock.On call
//   - ctx context.Context
//   - models []borrower.Borrower
//   - trx *gorm.DB
func (_e *MockIBorrowerRepository_Expecter) CreateBulkWithTx(ctx interface{}, models interface{}, trx interface{}) *MockIBorrowerRepository_CreateBulkWithTx_Call {
	return &MockIBorrowerRepository_CreateBulkWithTx_Call{Call: _e.mock.On("CreateBulkWithTx", ctx, models, trx)}
}

func (_c *MockIBorrowerRepository_CreateBulkWithTx_Call) Run(run func(ctx context.Context, models []borrower.Borrower, trx *gorm.DB)) *MockIBorrowerRepository_CreateBulkWithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []borrower.Borrower
		if args[1] != nil {
			arg1 = args[1].([]borrower.Borrower)
		}
		var arg2 *gorm.DB
		if args[2] != nil {
			arg2 = args[2].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIBorrowerRepository_CreateBulkWithTx_Call) Return(err error) *MockIBorrowerRepository_CreateBulkWithTx_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIBorrowerRepository_CreateBulkWithTx_Call) RunAndReturn(run func(ctx context.Context, models []borrower.Borrower, trx *gorm.DB) error) *MockIBorrowerRepository_CreateBulkWithTx_Call {
	_c.Call.Return(run)
	return _c
}

// CreateWithTx provides a mock function for the type MockIBorrowerRepository
func (_mock *MockIBorrowerRepository) CreateWithTx(ctx context.Context, model borrower.Borrower, trx *gorm.DB) (borrower.Borrower, error) {
	ret := _mock.Called(ctx, model, trx)

	if len(ret) == 0 {
		panic("no return value specified for CreateWithTx")
	}

	var r0 borrower.Borrower
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, borrower.Borrower, *gorm.DB) (borrower.Borrower, error)); ok {
		return returnFunc(ctx, model, trx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, borrower.Borrower, *gorm.DB) borrower.Borrower); ok {
		r0 = returnFunc(ctx, model, trx)
	} else {
		r0 = ret.Get(0).(borrower.Borrower)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, borrower.Borrower, *gorm.DB) error); ok {
		r1 = returnFunc(ctx, model, trx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIBorrowerRepository_CreateWithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWithTx'
type MockIBorrowerRepository_CreateWithTx_Call struct {
	*mock.Call
}

// CreateWithTx is a helper method to define mock.On call
//   - ctx context.Context
//   - model borrower.Borrower
//   - trx *gorm.DB
func (_e *MockIBorrowerRepository_Expecter) CreateWithTx(ctx interface{}, model interface{}, trx interface{}) *MockIBorrowerRepository_CreateWithTx_Call {
	return &MockIBorrowerRepository_CreateWithTx_Call{Call: _e.mock.On("CreateWithTx", ctx, model, trx)}
}

func (_c *MockIBorrowerRepository_CreateWithTx_Call) Run(run func(ctx context.Context, model borrower.Borrower, trx *gorm.DB)) *MockIBorrowerRepository_CreateWithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 borrower.Borrower
		if args[1] != nil {
			arg1 = args[1].(borrower.Borrower)
		}
		var arg2 *gorm.DB
		if args[2] != nil {
			arg2 = args[2].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIBorrowerRepository_CreateWithTx_Call) Return(borrower1 borrower.Borrower, err error) *MockIBorrowerRepository_CreateWithTx_Call {
	_c.Call.Return(borrower1, err)
	return _c
}

func (_c *MockIBorrowerRepository_CreateWithTx_Call) RunAndReturn(run func(ctx context.Context, model borrower.Borrower, trx *gorm.DB) (borrower.Borrower, error)) *MockIBorrowerRepository_CreateWithTx_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockIBorrowerRepository
func (_mock *MockIBorrowerRepository) Delete(ctx context.Context, ID uuid.UUID) error {
	ret := _mock.Called(ctx, ID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, ID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIBorrowerRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockIBorrowerRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - ID uuid.UUID
func (_e *MockIBorrowerRepository_Expecter) Delete(ctx interface{}, ID interface{}) *MockIBorrowerRepository_Delete_Call {
	return &MockIBorrowerRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, ID)}
}

func (_c *MockIBorrowerRepository_Delete_Call) Run(run func(ctx context.Context, ID uuid.UUID)) *MockIBorrowerRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIBorrowerRepository_Delete_Call) Return(err error) *MockIBorrowerRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIBorrowerRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, ID uuid.UUID) error) *MockIBorrowerRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteBulk provides a mock function for the type MockIBorrowerRepository
func (_mock *MockIBorrowerRepository) DeleteBulk(ctx context.Context, IDs []uuid.UUID) error {
	ret := _mock.Called(ctx, IDs)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBulk")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) error); ok {
		r0 = returnFunc(ctx, IDs)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIBorrowerRepository_DeleteBulk_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBulk'
type MockIBorrowerRepository_DeleteBulk_Call struct {
	*mock.Call
}

// DeleteBulk is a helper method to define mock.On call
//   - ctx context.Context
//   - IDs []uuid.UUID
func (_e *MockIBorrowerRepository_Expecter) DeleteBulk(ctx interface{}, IDs interface{}) *MockIBorrowerRepository_DeleteBulk_Call {
	return &MockIBorrowerRepository_DeleteBulk_Call{Call: _e.mock.On("DeleteBulk", ctx, IDs)}
}

func (_c *MockIBorrowerRepository_DeleteBulk_Call) Run(run func(ctx context.Context, IDs []uuid.UUID)) *MockIBorrowerRepository_DeleteBulk_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIBorrowerRepository_DeleteBulk_Call) Return(err error) *MockIBorrowerRepository_DeleteBulk_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIBorrowerRepository_DeleteBulk_Call) RunAndReturn(run func(ctx context.Context, IDs []uuid.UUID) error) *MockIBorrowerRepository_DeleteBulk_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteBulkWithTx provides a mock function for the type MockIBorrowerRepository
func (_mock *MockIBorrowerRepository) DeleteBulkWithTx(ctx context.Context, IDs []uuid.UUID, trx *gorm.DB) error {
	ret := _mock.Called(ctx, IDs, trx)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBulkWithTx")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID, *gorm.DB) error); ok {
		r0 = returnFunc(ctx, IDs, trx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIBorrowerRepository_DeleteBulkWithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBulkWithTx'
type MockIBorrowerRepository_DeleteBulkWithTx_Call struct {
	*mock.Call
}

// DeleteBulkWithTx is a helper method to define mock.On call
//   - ctx context.Context
//   - IDs []uuid.UUID
//   - trx *gorm.DB
func (_e *MockIBorrowerRepository_Expecter) DeleteBulkWithTx(ctx interface{}, IDs interface{}, trx interface{}) *MockIBorrowerRepository_DeleteBulkWithTx_Call {
	return &MockIBorrowerRepository_DeleteBulkWithTx_Call{Call: _e.mock.On("DeleteBulkWithTx", ctx, IDs, trx)}
}

func (_c *MockIBorrowerRepository_DeleteBulkWithTx_Call) Run(run func(ctx context.Context, IDs []uuid.UUID, trx *gorm.DB)) *MockIBorrowerRepository_DeleteBulkWithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		var arg2 *gorm.DB
		if args[2] != nil {
			arg2 = args[2].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIBorrowerRepository_DeleteBulkWithTx_Call) Return(err error) *MockIBorrowerRepository_DeleteBulkWithTx_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIBorrowerRepository_DeleteBulkWithTx_Call) RunAndReturn(run func(ctx context.Context, IDs []uuid.UUID, trx *gorm.DB) error) *MockIBorrowerRepository_DeleteBulkWithTx_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteWithTx provides a mock function for the type MockIBorrowerRepository
func (_mock *MockIBorrowerRepository) DeleteWithTx(ctx context.Context, ID uuid.UUID, trx *gorm.DB) error {
	ret := _mock.Called(ctx, ID, trx)

	if len(ret) == 0 {
		panic("no return value specified for DeleteWithTx")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *gorm.DB) error); ok {
		r0 = returnFunc(ctx, ID, trx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIBorrowerRepository_DeleteWithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteWithTx'
type MockIBorrowerRepository_DeleteWithTx_Call struct {
	*mock.Call
}

// DeleteWithTx is a helper method to define mock.On call
//   - ctx context.Context
//   - ID uuid.UUID
//   - trx *gorm.DB
func (_e *MockIBorrowerRepository_Expecter) DeleteWithTx(ctx interface{}, ID interface{}, trx interface{}) *MockIBorrowerRepository_DeleteWithTx_Call {
	return &MockIBorrowerRepository_DeleteWithTx_Call{Call: _e.mock.On("DeleteWithTx", ctx, ID, trx)}
}

func (_c *MockIBorrowerRepository_DeleteWithTx_Call) Run(run func(ctx context.Context, ID uuid.UUID, trx *gorm.DB)) *MockIBorrowerRepository_DeleteWithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 *gorm.DB
		if args[2] != nil {
			arg2 = args[2].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIBorrowerRepository_DeleteWithTx_Call) Return(err error) *MockIBorrowerRepository_DeleteWithTx_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIBorrowerRepository_DeleteWithTx_Call) RunAndReturn(run func(ctx context.Context, ID uuid.UUID, trx *gorm.DB) error) *MockIBorrowerRepository_DeleteWithTx_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type MockIBorrowerRepository
func (_mock *MockIBorrowerRepository) GetAll(ctx context.Context) ([]borrower.Borrower, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []borrower.Borrower
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]borrower.Borrower, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []borrower.Borrower); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]borrower.Borrower)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIBorrowerRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockIBorrowerRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIBorrowerRepository_Expecter) GetAll(ctx interface{}) *MockIBorrowerRepository_GetAll_Call {
	return &MockIBorrowerRepository_GetAll_Call{Call: _e.mock.On("GetAll", ctx)}
}

func (_c *MockIBorrowerRepository_GetAll_Call) Run(run func(ctx context.Context)) *MockIBorrowerRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIBorrowerRepository_GetAll_Call) Return(borrowers []borrower.Borrower, err error) *MockIBorrowerRepository_GetAll_Call {
	_c.Call.Return(borrowers, err)
	return _c
}

func (_c *MockIBorrowerRepository_GetAll_Call) RunAndReturn(run func(ctx context.Context) ([]borrower.Borrower, error)) *MockIBorrowerRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockIBorrowerRepository
func (_mock *MockIBorrowerRepository) GetByID(ctx context.Context, ID uuid.UUID) (borrower.Borrower, error) {
	ret := _mock.Called(ctx, ID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 borrower.Borrower
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (borrower.Borrower, error)); ok {
		return returnFunc(ctx, ID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) borrower.Borrower); ok {
		r0 = returnFunc(ctx, ID)
	} else {
		r0 = ret.Get(0).(borrower.Borrower)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, ID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIBorrowerRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockIBorrowerRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - ID uuid.UUID
func (_e *MockIBorrowerRepository_Expecter) GetByID(ctx interface{}, ID interface{}) *MockIBorrowerRepository_GetByID_Call {
	return &MockIBorrowerRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, ID)}
}

func (_c *MockIBorrowerRepository_GetByID_Call) Run(run func(ctx context.Context, ID uuid.UUID)) *MockIBorrowerRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIBorrowerRepository_GetByID_Call) Return(borrower1 borrower.Borrower, err error) *MockIBorrowerRepository_GetByID_Call {
	_c.Call.Return(borrower1, err)
	return _c
}

func (_c *MockIBorrowerRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, ID uuid.UUID) (borrower.Borrower, error)) *MockIBorrowerRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByIDLockTx provides a mock function for the type MockIBorrowerRepository
func (_mock *MockIBorrowerRepository) GetByIDLockTx(ctx context.Context, ID uuid.UUID, trx *gorm.DB) (borrower.Borrower, error) {
	ret := _mock.Called(ctx, ID, trx)

	if len(ret) == 0 {
		panic("no return value specified for GetByIDLockTx")
	}

	var r0 borrower.Borrower
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *gorm.DB) (borrower.Borrower, error)); ok {
		return returnFunc(ctx, ID, trx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *gorm.DB) borrower.Borrower); ok {
		r0 = returnFunc(ctx, ID, trx)
	} else {
		r0 = ret.Get(0).(borrower.Borrower)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, *gorm.DB) error); ok {
		r1 = returnFunc(ctx, ID, trx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIBorrowerRepository_GetByIDLockTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByIDLockTx'
type MockIBorrowerRepository_GetByIDLockTx_Call struct {
	*mock.Call
}

// GetByIDLockTx is a helper method to define mock.On call
//   - ctx context.Context
//   - ID uuid.UUID
//   - trx *gorm.DB
func (_e *MockIBorrowerRepository_Expecter) GetByIDLockTx(ctx interface{}, ID interface{}, trx interface{}) *MockIBorrowerRepository_GetByIDLockTx_Call {
	return &MockIBorrowerRepository_GetByIDLockTx_Call{Call: _e.mock.On("GetByIDLockTx", ctx, ID, trx)}
}

func (_c *MockIBorrowerRepository_GetByIDLockTx_Call) Run(run func(ctx context.Context, ID uuid.UUID, trx *gorm.DB)) *MockIBorrowerRepository_GetByIDLockTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 *gorm.DB
		if args[2] != nil {
			arg2 = args[2].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIBorrowerRepository_GetByIDLockTx_Call) Return(borrower1 borrower.Borrower, err error) *MockIBorrowerRepository_GetByIDLockTx_Call {
	_c.Call.Return(borrower1, err)
	return _c
}

func (_c *MockIBorrowerRepository_GetByIDLockTx_Call) RunAndReturn(run func(ctx context.Context, ID uuid.UUID, trx *gorm.DB) (borrower.Borrower, error)) *MockIBorrowerRepository_GetByIDLockTx_Call {
	_c.Call.Return(run)
	return _c
}

// GetByIDs provides a mock function for the type MockIBorrowerRepository
func (_mock *MockIBorrowerRepository) GetByIDs(ctx context.Context, IDs []uuid.UUID) ([]borrower.Borrower, error) {
	ret := _mock.Called(ctx, IDs)

	if len(ret) == 0 {
		panic("no return value specified for GetByIDs")
	}

	var r0 []borrower.Borrower
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) ([]borrower.Borrower, error)); ok {
		return returnFunc(ctx, IDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) []borrower.Borrower); ok {
		r0 = returnFunc(ctx, IDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]borrower.Borrower)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []uuid.UUID) error); ok {
		r1 = returnFunc(ctx, IDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIBorrowerRepository_GetByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByIDs'
type MockIBorrowerRepository_GetByIDs_Call struct {
	*mock.Call
}

// GetByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - IDs []uuid.UUID
func (_e *MockIBorrowerRepository_Expecter) GetByIDs(ctx interface{}, IDs interface{}) *MockIBorrowerRepository_GetByIDs_Call {
	return &MockIBorrowerRepository_GetByIDs_Call{Call: _e.mock.On("GetByIDs", ctx, IDs)}
}

func (_c *MockIBorrowerRepository_GetByIDs_Call) Run(run func(ctx context.Context, IDs []uuid.UUID)) *MockIBorrowerRepository_GetByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIBorrowerRepository_GetByIDs_Call) Return(borrowers []borrower.Borrower, err error) *MockIBorrowerRepository_GetByIDs_Call {
	_c.Call.Return(borrowers, err)
	return _c
}

func (_c *MockIBorrowerRepository_GetByIDs_Call) RunAndReturn(run func(ctx context.Context, IDs []uuid.UUID) ([]borrower.Borrower, error)) *MockIBorrowerRepository_GetByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// Pagination provides a mock function for the type MockIBorrowerRepository
func (_mock *MockIBorrowerRepository) Pagination(ctx context.Context, filter map[string]any, page int, limit int) (repository.Pagination[borrower.Borrower], error) {
	ret := _mock.Called(ctx, filter, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for Pagination")
	}

	var r0 repository.Pagination[borrower.Borrower]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[string]any, int, int) (repository.Pagination[borrower.Borrower], error)); ok {
		return returnFunc(ctx, filter, page, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[string]any, int, int) repository.Pagination[borrower.Borrower]); ok {
		r0 = returnFunc(ctx, filter, page, limit)
	} else {
		r0 = ret.Get(0).(repository.Pagination[borrower.Borrower])
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, map[string]any, int, int) error); ok {
		r1 = returnFunc(ctx, filter, page, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIBorrowerRepository_Pagination_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pagination'
type MockIBorrowerRepository_Pagination_Call struct {
	*mock.Call
}

// Pagination is a helper method to define mock.On call
//   - ctx context.Context
//   - filter map[string]any
//   - page int
//   - limit int
func (_e *MockIBorrowerRepository_Expecter) Pagination(ctx interface{}, filter interface{}, page interface{}, limit interface{}) *MockIBorrowerRepository_Pagination_Call {
	return &MockIBorrowerRepository_Pagination_Call{Call: _e.mock.On("Pagination", ctx, filter, page, limit)}
}

func (_c *MockIBorrowerRepository_Pagination_Call) Run(run func(ctx context.Context, filter map[string]any, page int, limit int)) *MockIBorrowerRepository_Pagination_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 map[string]any
		if args[1] != nil {
			arg1 = args[1].(map[string]any)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockIBorrowerRepository_Pagination_Call) Return(res repository.Pagination[borrower.Borrower], err error) *MockIBorrowerRepository_Pagination_Call {
	_c.Call.Return(res, err)
	return _c
}

func (_c *MockIBorrowerRepository_Pagination_Call) RunAndReturn(run func(ctx context.Context, filter map[string]any, page int, limit int) (repository.Pagination[borrower.Borrower], error)) *MockIBorrowerRepository_Pagination_Call {
	_c.Call.Return(run)
	return _c
}

// Rollback provides a mock function for the type MockIBorrowerRepository
func (_mock *MockIBorrowerRepository) Rollback(trx *gorm.DB) *gorm.DB {
	ret := _mock.Called(trx)

	if len(ret) == 0 {
		panic("no return value specified for Rollback")
	}

	var r0 *gorm.DB
	if returnFunc, ok := ret.Get(0).(func(*gorm.DB) *gorm.DB); ok {
		r0 = returnFunc(trx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}
	return r0
}

// MockIBorrowerRepository_Rollback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rollback'
type MockIBorrowerRepository_Rollback_Call struct {
	*mock.Call
}

// Rollback is a helper method to define mock.On call
//   - trx *gorm.DB
func (_e *MockIBorrowerRepository_Expecter) Rollback(trx interface{}) *MockIBorrowerRepository_Rollback_Call {
	return &MockIBorrowerRepository_Rollback_Call{Call: _e.mock.On("Rollback", trx)}
}

func (_c *MockIBorrowerRepository_Rollback_Call) Run(run func(trx *gorm.DB)) *MockIBorrowerRepository_Rollback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIBorrowerRepository_Rollback_Call) Return(dB *gorm.DB) *MockIBorrowerRepository_Rollback_Call {
	_c.Call.Return(dB)
	return _c
}

func (_c *MockIBorrowerRepository_Rollback_Call) RunAndReturn(run func(trx *gorm.DB) *gorm.DB) *MockIBorrowerRepository_Rollback_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockIBorrowerRepository
func (_mock *MockIBorrowerRepository) Update(ctx context.Context, ID uuid.UUID, model borrower.Borrower) (borrower.Borrower, error) {
	ret := _mock.Called(ctx, ID, model)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 borrower.Borrower
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, borrower.Borrower) (borrower.Borrower, error)); ok {
		return returnFunc(ctx, ID, model)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, borrower.Borrower) borrower.Borrower); ok {
		r0 = returnFunc(ctx, ID, model)
	} else {
		r0 = ret.Get(0).(borrower.Borrower)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, borrower.Borrower) error); ok {
		r1 = returnFunc(ctx, ID, model)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIBorrowerRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockIBorrowerRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - ID uuid.UUID
//   - model borrower.Borrower
func (_e *MockIBorrowerRepository_Expecter) Update(ctx interface{}, ID interface{}, model interface{}) *MockIBorrowerRepository_Update_Call {
	return &MockIBorrowerRepository_Update_Call{Call: _e.mock.On("Update", ctx, ID, model)}
}

func (_c *MockIBorrowerRepository_Update_Call) Run(run func(ctx context.Context, ID uuid.UUID, model borrower.Borrower)) *MockIBorrowerRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 borrower.Borrower
		if args[2] != nil {
			arg2 = args[2].(borrower.Borrower)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIBorrowerRepository_Update_Call) Return(borrower1 borrower.Borrower, err error) *MockIBorrowerRepository_Update_Call {
	_c.Call.Return(borrower1, err)
	return _c
}

func (_c *MockIBorrowerRepository_Update_Call) RunAndReturn(run func(ctx context.Context, ID uuid.UUID, model borrower.Borrower) (borrower.Borrower, error)) *MockIBorrowerRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateBulk provides a mock function for the type MockIBorrowerRepository
func (_mock *MockIBorrowerRepository) UpdateBulk(ctx context.Context, IDs []uuid.UUID, payload map[string]any) error {
	ret := _mock.Called(ctx, IDs, payload)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBulk")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID, map[string]any) error); ok {
		r0 = returnFunc(ctx, IDs, payload)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIBorrowerRepository_UpdateBulk_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateBulk'
type MockIBorrowerRepository_UpdateBulk_Call struct {
	*mock.Call
}

// UpdateBulk is a helper method to define mock.On call
//   - ctx context.Context
//   - IDs []uuid.UUID
//   - payload map[string]any
func (_e *MockIBorrowerRepository_Expecter) UpdateBulk(ctx interface{}, IDs interface{}, payload interface{}) *MockIBorrowerRepository_UpdateBulk_Call {
	return &MockIBorrowerRepository_UpdateBulk_Call{Call: _e.mock.On("UpdateBulk", ctx, IDs, payload)}
}

func (_c *MockIBorrowerRepository_UpdateBulk_Call) Run(run func(ctx context.Context, IDs []uuid.UUID, payload map[string]any)) *MockIBorrowerRepository_UpdateBulk_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		var arg2 map[string]any
		if args[2] != nil {
			arg2 = args[2].(map[string]any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIBorrowerRepository_UpdateBulk_Call) Return(err error) *MockIBorrowerRepository_UpdateBulk_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIBorrowerRepository_UpdateBulk_Call) RunAndReturn(run func(ctx context.Context, IDs []uuid.UUID, payload map[string]any) error) *MockIBorrowerRepository_UpdateBulk_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateBulkWithTx provides a mock function for the type MockIBorrowerRepository
func (_mock *MockIBorrowerRepository) UpdateBulkWithTx(ctx context.Context, IDs []uuid.UUID, payload map[string]any, trx *gorm.DB) error {
	ret := _mock.Called(ctx, IDs, payload, trx)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBulkWithTx")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID, map[string]any, *gorm.DB) error); ok {
		r0 = returnFunc(ctx, IDs, payload, trx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIBorrowerRepository_UpdateBulkWithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateBulkWithTx'
type MockIBorrowerRepository_UpdateBulkWithTx_Call struct {
	*mock.Call
}

// UpdateBulkWithTx is a helper method to define mock.On call
//   - ctx context.Context
//   - IDs []uuid.UUID
//   - payload map[string]any
//   - trx *gorm.DB
func (_e *MockIBorrowerRepository_Expecter) UpdateBulkWithTx(ctx interface{}, IDs interface{}, payload interface{}, trx interface{}) *MockIBorrowerRepository_UpdateBulkWithTx_Call {
	return &MockIBorrowerRepository_UpdateBulkWithTx_Call{Call: _e.mock.On("UpdateBulkWithTx", ctx, IDs, payload, trx)}
}

func (_c *MockIBorrowerRepository_UpdateBulkWithTx_Call) Run(run func(ctx context.Context, IDs []uuid.UUID, payload map[string]any, trx *gorm.DB)) *MockIBorrowerRepository_UpdateBulkWithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		var arg2 map[string]any
		if args[2] != nil {
			arg2 = args[2].(map[string]any)
		}
		var arg3 *gorm.DB
		if args[3] != nil {
			arg3 = args[3].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockIBorrowerRepository_UpdateBulkWithTx_Call) Return(err error) *MockIBorrowerRepository_UpdateBulkWithTx_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIBorrowerRepository_UpdateBulkWithTx_Call) RunAndReturn(run func(ctx context.Context, IDs []uuid.UUID, payload map[string]any, trx *gorm.DB) error) *MockIBorrowerRepository_UpdateBulkWithTx_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateWithMap provides a mock function for the type MockIBorrowerRepository
func (_mock *MockIBorrowerRepository) UpdateWithMap(ctx context.Context, ID uuid.UUID, payload map[string]any) (borrower.Borrower, error) {
	ret := _mock.Called(ctx, ID, payload)

	if len(ret) == 0 {
		panic("no return value specified for UpdateWithMap")
	}

	var r0 borrower.Borrower
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, map[string]any) (borrower.Borrower, error)); ok {
		return returnFunc(ctx, ID, payload)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, map[string]any) borrower.Borrower); ok {
		r0 = returnFunc(ctx, ID, payload)
	} else {
		r0 = ret.Get(0).(borrower.Borrower)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, map[string]any) error); ok {
		r1 = returnFunc(ctx, ID, payload)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIBorrowerRepository_UpdateWithMap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateWithMap'
type MockIBorrowerRepository_UpdateWithMap_Call struct {
	*mock.Call
}

// UpdateWithMap is a helper method to define mock.On call
//   - ctx context.Context
//   - ID uuid.UUID
//   - payload map[string]any
func (_e *MockIBorrowerRepository_Expecter) UpdateWithMap(ctx interface{}, ID interface{}, payload interface{}) *MockIBorrowerRepository_UpdateWithMap_Call {
	return &MockIBorrowerRepository_UpdateWithMap_Call{Call: _e.mock.On("UpdateWithMap", ctx, ID, payload)}
}

func (_c *MockIBorrowerRepository_UpdateWithMap_Call) Run(run func(ctx context.Context, ID uuid.UUID, payload map[string]any)) *MockIBorrowerRepository_UpdateWithMap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 map[string]any
		if args[2] != nil {
			arg2 = args[2].(map[string]any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIBorrowerRepository_UpdateWithMap_Call) Return(borrower1 borrower.Borrower, err error) *MockIBorrowerRepository_UpdateWithMap_Call {
	_c.Call.Return(borrower1, err)
	return _c
}

func (_c *MockIBorrowerRepository_UpdateWithMap_Call) RunAndReturn(run func(ctx context.Context, ID uuid.UUID, payload map[string]any) (borrower.Borrower, error)) *MockIBorrowerRepository_UpdateWithMap_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateWithMapTx provides a mock function for the type MockIBorrowerRepository
func (_mock *MockIBorrowerRepository) UpdateWithMapTx(ctx context.Context, ID uuid.UUID, payload map[string]any, trx *gorm.DB) (borrower.Borrower, error) {
	ret := _mock.Called(ctx, ID, payload, trx)

	if len(ret) == 0 {
		panic("no return value specified for UpdateWithMapTx")
	}

	var r0 borrower.Borrower
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, map[string]any, *gorm.DB) (borrower.Borrower, error)); ok {
		return returnFunc(ctx, ID, payload, trx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, map[string]any, *gorm.DB) borrower.Borrower); ok {
		r0 = returnFunc(ctx, ID, payload, trx)
	} else {
		r0 = ret.Get(0).(borrower.Borrower)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, map[string]any, *gorm.DB) error); ok {
		r1 = returnFunc(ctx, ID, payload, trx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIBorrowerRepository_UpdateWithMapTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateWithMapTx'
type MockIBorrowerRepository_UpdateWithMapTx_Call struct {
	*mock.Call
}

// UpdateWithMapTx is a helper method to define mock.On call
//   - ctx context.Context
//   - ID uuid.UUID
//   - payload map[string]any
//   - trx *gorm.DB
func (_e *MockIBorrowerRepository_Expecter) UpdateWithMapTx(ctx interface{}, ID interface{}, payload interface{}, trx interface{}) *MockIBorrowerRepository_UpdateWithMapTx_Call {
	return &MockIBorrowerRepository_UpdateWithMapTx_Call{Call: _e.mock.On("UpdateWithMapTx", ctx, ID, payload, trx)}
}

func (_c *MockIBorrowerRepository_UpdateWithMapTx_Call) Run(run func(ctx context.Context, ID uuid.UUID, payload map[string]any, trx *gorm.DB)) *MockIBorrowerRepository_UpdateWithMapTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 map[string]any
		if args[2] != nil {
			arg2 = args[2].(map[string]any)
		}
		var arg3 *gorm.DB
		if args[3] != nil {
			arg3 = args[3].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockIBorrowerRepository_UpdateWithMapTx_Call) Return(borrower1 borrower.Borrower, err error) *MockIBorrowerRepository_UpdateWithMapTx_Call {
	_c.Call.Return(borrower1, err)
	return _c
}

func (_c *MockIBorrowerRepository_UpdateWithMapTx_Call) RunAndReturn(run func(ctx context.Context, ID uuid.UUID, payload map[string]any, trx *gorm.DB) (borrower.Borrower, error)) *MockIBorrowerRepository_UpdateWithMapTx_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateWithTx provides a mock function for the type MockIBorrowerRepository
func (_mock *MockIBorrowerRepository) UpdateWithTx(ctx context.Context, ID uuid.UUID, model borrower.Borrower, trx *gorm.DB) (borrower.Borrower, error) {
	ret := _mock.Called(ctx, ID, model, trx)

	if len(ret) == 0 {
		panic("no return value specified for UpdateWithTx")
	}

	var r0 borrower.Borrower
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, borrower.Borrower, *gorm.DB) (borrower.Borrower, error)); ok {
		return returnFunc(ctx, ID, model, trx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, borrower.Borrower, *gorm.DB) borrower.Borrower); ok {
		r0 = returnFunc(ctx, ID, model, trx)
	} else {
		r0 = ret.Get(0).(borrower.Borrower)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, borrower.Borrower, *gorm.DB) error); ok {
		r1 = returnFunc(ctx, ID, model, trx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIBorrowerRepository_UpdateWithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateWithTx'
type MockIBorrowerRepository_UpdateWithTx_Call struct {
	*mock.Call
}

// UpdateWithTx is a helper method to define mock.On call
//   - ctx context.Context
//   - ID uuid.UUID
//   - model borrower.Borrower
//   - trx *gorm.DB
func (_e *MockIBorrowerRepository_Expecter) UpdateWithTx(ctx interface{}, ID interface{}, model interface{}, trx interface{}) *MockIBorrowerRepository_UpdateWithTx_Call {
	return &MockIBorrowerRepository_UpdateWithTx_Call{Call: _e.mock.On("UpdateWithTx", ctx, ID, model, trx)}
}

func (_c *MockIBorrowerRepository_UpdateWithTx_Call) Run(run func(ctx context.Context, ID uuid.UUID, model borrower.Borrower, trx *gorm.DB)) *MockIBorrowerRepository_UpdateWithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 borrower.Borrower
		if args[2] != nil {
			arg2 = args[2].(borrower.Borrower)
		}
		var arg3 *gorm.DB
		if args[3] != nil {
			arg3 = args[3].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockIBorrowerRepository_UpdateWithTx_Call) Return(borrower1 borrower.Borrower, err error) *MockIBorrowerRepository_UpdateWithTx_Call {
	_c.Call.Return(borrower1, err)
	return _c
}

func (_c *MockIBorrowerRepository_UpdateWithTx_Call) RunAndReturn(run func(ctx context.Context, ID uuid.UUID, model borrower.Borrower, trx *gorm.DB) (borrower.Borrower, error)) *MockIBorrowerRepository_UpdateWithTx_Call {
	_c.Call.Return(run)
	return _c
}
