// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package employee

import (
	"context"

	"github.com/BagusAK95/amarta_test/internal/domain/common/repository"
	"github.com/BagusAK95/amarta_test/internal/domain/employee"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
	"gorm.io/gorm"
)

// NewMockIEmployeeRepository creates a new instance of MockIEmployeeRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIEmployeeRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIEmployeeRepository {
	mock := &MockIEmployeeRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIEmployeeRepository is an autogenerated mock type for the IEmployeeRepository type
type MockIEmployeeRepository struct {
	mock.Mock
}

type MockIEmployeeRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIEmployeeRepository) EXPECT() *MockIEmployeeRepository_Expecter {
	return &MockIEmployeeRepository_Expecter{mock: &_m.Mock}
}

// BeginTransaction provides a mock function for the type MockIEmployeeRepository
func (_mock *MockIEmployeeRepository) BeginTransaction(ctx context.Context) *gorm.DB {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for BeginTransaction")
	}

	var r0 *gorm.DB
	if returnFunc, ok := ret.Get(0).(func(context.Context) *gorm.DB); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}
	return r0
}

// MockIEmployeeRepository_BeginTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginTransaction'
type MockIEmployeeRepository_BeginTransaction_Call struct {
	*mock.Call
}

// BeginTransaction is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIEmployeeRepository_Expecter) BeginTransaction(ctx interface{}) *MockIEmployeeRepository_BeginTransaction_Call {
	return &MockIEmployeeRepository_BeginTransaction_Call{Call: _e.mock.On("BeginTransaction", ctx)}
}

func (_c *MockIEmployeeRepository_BeginTransaction_Call) Run(run func(ctx context.Context)) *MockIEmployeeRepository_BeginTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIEmployeeRepository_BeginTransaction_Call) Return(dB *gorm.DB) *MockIEmployeeRepository_BeginTransaction_Call {
	_c.Call.Return(dB)
	return _c
}

func (_c *MockIEmployeeRepository_BeginTransaction_Call) RunAndReturn(run func(ctx context.Context) *gorm.DB) *MockIEmployeeRepository_BeginTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// Commit provides a mock function for the type MockIEmployeeRepository
func (_mock *MockIEmployeeRepository) Commit(trx *gorm.DB) *gorm.DB {
	ret := _mock.Called(trx)

	if len(ret) == 0 {
		panic("no return value specified for Commit")
	}

	var r0 *gorm.DB
	if returnFunc, ok := ret.Get(0).(func(*gorm.DB) *gorm.DB); ok {
		r0 = returnFunc(trx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}
	return r0
}

// MockIEmployeeRepository_Commit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Commit'
type MockIEmployeeRepository_Commit_Call struct {
	*mock.Call
}

// Commit is a helper method to define mock.On call
//   - trx *gorm.DB
func (_e *MockIEmployeeRepository_Expecter) Commit(trx interface{}) *MockIEmployeeRepository_Commit_Call {
	return &MockIEmployeeRepository_Commit_Call{Call: _e.mock.On("Commit", trx)}
}

func (_c *MockIEmployeeRepository_Commit_Call) Run(run func(trx *gorm.DB)) *MockIEmployeeRepository_Commit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIEmployeeRepository_Commit_Call) Return(dB *gorm.DB) *MockIEmployeeRepository_Commit_Call {
	_c.Call.Return(dB)
	return _c
}

func (_c *MockIEmployeeRepository_Commit_Call) RunAndReturn(run func(trx *gorm.DB) *gorm.DB) *MockIEmployeeRepository_Commit_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockIEmployeeRepository
func (_mock *MockIEmployeeRepository) Create(ctx context.Context, model employee.Employee) (employee.Employee, error) {
	ret := _mock.Called(ctx, model)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 employee.Employee
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, employee.Employee) (employee.Employee, error)); ok {
		return returnFunc(ctx, model)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, employee.Employee) employee.Employee); ok {
		r0 = returnFunc(ctx, model)
	} else {
		r0 = ret.Get(0).(employee.Employee)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, employee.Employee) error); ok {
		r1 = returnFunc(ctx, model)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIEmployeeRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIEmployeeRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - model employee.Employee
func (_e *MockIEmployeeRepository_Expecter) Create(ctx interface{}, model interface{}) *MockIEmployeeRepository_Create_Call {
	return &MockIEmployeeRepository_Create_Call{Call: _e.mock.On("Create", ctx, model)}
}

func (_c *MockIEmployeeRepository_Create_Call) Run(run func(ctx context.Context, model employee.Employee)) *MockIEmployeeRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 employee.Employee
		if args[1] != nil {
			arg1 = args[1].(employee.Employee)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIEmployeeRepository_Create_Call) Return(employee1 employee.Employee, err error) *MockIEmployeeRepository_Create_Call {
	_c.Call.Return(employee1, err)
	return _c
}

func (_c *MockIEmployeeRepository_Create_Call) RunAndReturn(run func(ctx context.Context, model employee.Employee) (employee.Employee, error)) *MockIEmployeeRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateBulk provides a mock function for the type MockIEmployeeRepository
func (_mock *MockIEmployeeRepository) CreateBulk(ctx context.Context, models []employee.Employee) error {
	ret := _mock.Called(ctx, models)

	if len(ret) == 0 {
		panic("no return value specified for CreateBulk")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []employee.Employee) error); ok {
		r0 = returnFunc(ctx, models)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIEmployeeRepository_CreateBulk_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBulk'
type MockIEmployeeRepository_CreateBulk_Call struct {
	*mock.Call
}

// CreateBulk is a helper method to define mock.On call
//   - ctx context.Context
//   - models []employee.Employee
func (_e *MockIEmployeeRepository_Expecter) CreateBulk(ctx interface{}, models interface{}) *MockIEmployeeRepository_CreateBulk_Call {
	return &MockIEmployeeRepository_CreateBulk_Call{Call: _e.mock.On("CreateBulk", ctx, models)}
}

func (_c *MockIEmployeeRepository_CreateBulk_Call) Run(run func(ctx context.Context, models []employee.Employee)) *MockIEmployeeRepository_CreateBulk_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []employee.Employee
		if args[1] != nil {
			arg1 = args[1].([]employee.Employee)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIEmployeeRepository_CreateBulk_Call) Return(err error) *MockIEmployeeRepository_CreateBulk_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIEmployeeRepository_CreateBulk_Call) RunAndReturn(run func(ctx context.Context, models []employee.Employee) error) *MockIEmployeeRepository_CreateBulk_Call {
	_c.Call.Return(run)
	return _c
}

// CreateBulkAndReturnWithTx provides a mock function for the type MockIEmployeeRepository
func (_mock *MockIEmployeeRepository) CreateBulkAndReturnWithTx(ctx context.Context, models []employee.Employee, trx *gorm.DB) ([]employee.Employee, error) {
	ret := _mock.Called(ctx, models, trx)

	if len(ret) == 0 {
		panic("no return value specified for CreateBulkAndReturnWithTx")
	}

	var r0 []employee.Employee
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []employee.Employee, *gorm.DB) ([]employee.Employee, error)); ok {
		return returnFunc(ctx, models, trx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []employee.Employee, *gorm.DB) []employee.Employee); ok {
		r0 = returnFunc(ctx, models, trx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]employee.Employee)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []employee.Employee, *gorm.DB) error); ok {
		r1 = returnFunc(ctx, models, trx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIEmployeeRepository_CreateBulkAndReturnWithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBulkAndReturnWithTx'
type MockIEmployeeRepository_CreateBulkAndReturnWithTx_Call struct {
	*mock.Call
}

// CreateBulkAndReturnWithTx is a helper method to define mock.On call
//   - ctx context.Context
//   - models []employee.Employee
//   - trx *gorm.DB
func (_e *MockIEmployeeRepository_Expecter) CreateBulkAndReturnWithTx(ctx interface{}, models interface{}, trx interface{}) *MockIEmployeeRepository_CreateBulkAndReturnWithTx_Call {
	return &MockIEmployeeRepository_CreateBulkAndReturnWithTx_Call{Call: _e.mock.On("CreateBulkAndReturnWithTx", ctx, models, trx)}
}

func (_c *MockIEmployeeRepository_CreateBulkAndReturnWithTx_Call) Run(run func(ctx context.Context, models []employee.Employee, trx *gorm.DB)) *MockIEmployeeRepository_CreateBulkAndReturnWithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []employee.Employee
		if args[1] != nil {
			arg1 = args[1].([]employee.Employee)
		}
		var arg2 *gorm.DB
		if args[2] != nil {
			arg2 = args[2].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIEmployeeRepository_CreateBulkAndReturnWithTx_Call) Return(employees []employee.Employee, err error) *MockIEmployeeRepository_CreateBulkAndReturnWithTx_Call {
	_c.Call.Return(employees, err)
	return _c
}

func (_c *MockIEmployeeRepository_CreateBulkAndReturnWithTx_Call) RunAndReturn(run func(ctx context.Context, models []employee.Employee, trx *gorm.DB) ([]employee.Employee, error)) *MockIEmployeeRepository_CreateBulkAndReturnWithTx_Call {
	_c.Call.Return(run)
	return _c
}

// CreateBulkWithTx provides a mock function for the type MockIEmployeeRepository
func (_mock *MockIEmployeeRepository) CreateBulkWithTx(ctx context.Context, models []employee.Employee, trx *gorm.DB) error {
	ret := _mock.Called(ctx, models, trx)

	if len(ret) == 0 {
		panic("no return value specified for CreateBulkWithTx")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []employee.Employee, *gorm.DB) error); ok {
		r0 = returnFunc(ctx, models, trx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIEmployeeRepository_CreateBulkWithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBulkWithTx'
type MockIEmployeeRepository_CreateBulkWithTx_Call struct {
	*mock.Call
}

// CreateBulkWithTx is a helper method to define mock.On call
//   - ctx context.Context
//   - models []employee.Employee
//   - trx *gorm.DB
func (_e *MockIEmployeeRepository_Expecter) CreateBulkWithTx(ctx interface{}, models interface{}, trx interface{}) *MockIEmployeeRepository_CreateBulkWithTx_Call {
	return &MockIEmployeeRepository_CreateBulkWithTx_Call{Call: _e.mock.On("CreateBulkWithTx", ctx, models, trx)}
}

func (_c *MockIEmployeeRepository_CreateBulkWithTx_Call) Run(run func(ctx context.Context, models []employee.Employee, trx *gorm.DB)) *MockIEmployeeRepository_CreateBulkWithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []employee.Employee
		if args[1] != nil {
			arg1 = args[1].([]employee.Employee)
		}
		var arg2 *gorm.DB
		if args[2] != nil {
			arg2 = args[2].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIEmployeeRepository_CreateBulkWithTx_Call) Return(err error) *MockIEmployeeRepository_CreateBulkWithTx_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIEmployeeRepository_CreateBulkWithTx_Call) RunAndReturn(run func(ctx context.Context, models []employee.Employee, trx *gorm.DB) error) *MockIEmployeeRepository_CreateBulkWithTx_Call {
	_c.Call.Return(run)
	return _c
}

// CreateWithTx provides a mock function for the type MockIEmployeeRepository
func (_mock *MockIEmployeeRepository) CreateWithTx(ctx context.Context, model employee.Employee, trx *gorm.DB) (employee.Employee, error) {
	ret := _mock.Called(ctx, model, trx)

	if len(ret) == 0 {
		panic("no return value specified for CreateWithTx")
	}

	var r0 employee.Employee
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, employee.Employee, *gorm.DB) (employee.Employee, error)); ok {
		return returnFunc(ctx, model, trx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, employee.Employee, *gorm.DB) employee.Employee); ok {
		r0 = returnFunc(ctx, model, trx)
	} else {
		r0 = ret.Get(0).(employee.Employee)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, employee.Employee, *gorm.DB) error); ok {
		r1 = returnFunc(ctx, model, trx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIEmployeeRepository_CreateWithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWithTx'
type MockIEmployeeRepository_CreateWithTx_Call struct {
	*mock.Call
}

// CreateWithTx is a helper method to define mock.On call
//   - ctx context.Context
//   - model employee.Employee
//   - trx *gorm.DB
func (_e *MockIEmployeeRepository_Expecter) CreateWithTx(ctx interface{}, model interface{}, trx interface{}) *MockIEmployeeRepository_CreateWithTx_Call {
	return &MockIEmployeeRepository_CreateWithTx_Call{Call: _e.mock.On("CreateWithTx", ctx, model, trx)}
}

func (_c *MockIEmployeeRepository_CreateWithTx_Call) Run(run func(ctx context.Context, model employee.Employee, trx *gorm.DB)) *MockIEmployeeRepository_CreateWithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 employee.Employee
		if args[1] != nil {
			arg1 = args[1].(employee.Employee)
		}
		var arg2 *gorm.DB
		if args[2] != nil {
			arg2 = args[2].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIEmployeeRepository_CreateWithTx_Call) Return(employee1 employee.Employee, err error) *MockIEmployeeRepository_CreateWithTx_Call {
	_c.Call.Return(employee1, err)
	return _c
}

func (_c *MockIEmployeeRepository_CreateWithTx_Call) RunAndReturn(run func(ctx context.Context, model employee.Employee, trx *gorm.DB) (employee.Employee, error)) *MockIEmployeeRepository_CreateWithTx_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockIEmployeeRepository
func (_mock *MockIEmployeeRepository) Delete(ctx context.Context, ID uuid.UUID) error {
	ret := _mock.Called(ctx, ID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, ID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIEmployeeRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockIEmployeeRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - ID uuid.UUID
func (_e *MockIEmployeeRepository_Expecter) Delete(ctx interface{}, ID interface{}) *MockIEmployeeRepository_Delete_Call {
	return &MockIEmployeeRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, ID)}
}

func (_c *MockIEmployeeRepository_Delete_Call) Run(run func(ctx context.Context, ID uuid.UUID)) *MockIEmployeeRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIEmployeeRepository_Delete_Call) Return(err error) *MockIEmployeeRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIEmployeeRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, ID uuid.UUID) error) *MockIEmployeeRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteBulk provides a mock function for the type MockIEmployeeRepository
func (_mock *MockIEmployeeRepository) DeleteBulk(ctx context.Context, IDs []uuid.UUID) error {
	ret := _mock.Called(ctx, IDs)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBulk")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) error); ok {
		r0 = returnFunc(ctx, IDs)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIEmployeeRepository_DeleteBulk_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBulk'
type MockIEmployeeRepository_DeleteBulk_Call struct {
	*mock.Call
}

// DeleteBulk is a helper method to define mock.On call
//   - ctx context.Context
//   - IDs []uuid.UUID
func (_e *MockIEmployeeRepository_Expecter) DeleteBulk(ctx interface{}, IDs interface{}) *MockIEmployeeRepository_DeleteBulk_Call {
	return &MockIEmployeeRepository_DeleteBulk_Call{Call: _e.mock.On("DeleteBulk", ctx, IDs)}
}

func (_c *MockIEmployeeRepository_DeleteBulk_Call) Run(run func(ctx context.Context, IDs []uuid.UUID)) *MockIEmployeeRepository_DeleteBulk_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIEmployeeRepository_DeleteBulk_Call) Return(err error) *MockIEmployeeRepository_DeleteBulk_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIEmployeeRepository_DeleteBulk_Call) RunAndReturn(run func(ctx context.Context, IDs []uuid.UUID) error) *MockIEmployeeRepository_DeleteBulk_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteBulkWithTx provides a mock function for the type MockIEmployeeRepository
func (_mock *MockIEmployeeRepository) DeleteBulkWithTx(ctx context.Context, IDs []uuid.UUID, trx *gorm.DB) error {
	ret := _mock.Called(ctx, IDs, trx)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBulkWithTx")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID, *gorm.DB) error); ok {
		r0 = returnFunc(ctx, IDs, trx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIEmployeeRepository_DeleteBulkWithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBulkWithTx'
type MockIEmployeeRepository_DeleteBulkWithTx_Call struct {
	*mock.Call
}

// DeleteBulkWithTx is a helper method to define mock.On call
//   - ctx context.Context
//   - IDs []uuid.UUID
//   - trx *gorm.DB
func (_e *MockIEmployeeRepository_Expecter) DeleteBulkWithTx(ctx interface{}, IDs interface{}, trx interface{}) *MockIEmployeeRepository_DeleteBulkWithTx_Call {
	return &MockIEmployeeRepository_DeleteBulkWithTx_Call{Call: _e.mock.On("DeleteBulkWithTx", ctx, IDs, trx)}
}

func (_c *MockIEmployeeRepository_DeleteBulkWithTx_Call) Run(run func(ctx context.Context, IDs []uuid.UUID, trx *gorm.DB)) *MockIEmployeeRepository_DeleteBulkWithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		var arg2 *gorm.DB
		if args[2] != nil {
			arg2 = args[2].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIEmployeeRepository_DeleteBulkWithTx_Call) Return(err error) *MockIEmployeeRepository_DeleteBulkWithTx_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIEmployeeRepository_DeleteBulkWithTx_Call) RunAndReturn(run func(ctx context.Context, IDs []uuid.UUID, trx *gorm.DB) error) *MockIEmployeeRepository_DeleteBulkWithTx_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteWithTx provides a mock function for the type MockIEmployeeRepository
func (_mock *MockIEmployeeRepository) DeleteWithTx(ctx context.Context, ID uuid.UUID, trx *gorm.DB) error {
	ret := _mock.Called(ctx, ID, trx)

	if len(ret) == 0 {
		panic("no return value specified for DeleteWithTx")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *gorm.DB) error); ok {
		r0 = returnFunc(ctx, ID, trx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIEmployeeRepository_DeleteWithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteWithTx'
type MockIEmployeeRepository_DeleteWithTx_Call struct {
	*mock.Call
}

// DeleteWithTx is a helper method to define mock.On call
//   - ctx context.Context
//   - ID uuid.UUID
//   - trx *gorm.DB
func (_e *MockIEmployeeRepository_Expecter) DeleteWithTx(ctx interface{}, ID interface{}, trx interface{}) *MockIEmployeeRepository_DeleteWithTx_Call {
	return &MockIEmployeeRepository_DeleteWithTx_Call{Call: _e.mock.On("DeleteWithTx", ctx, ID, trx)}
}

func (_c *MockIEmployeeRepository_DeleteWithTx_Call) Run(run func(ctx context.Context, ID uuid.UUID, trx *gorm.DB)) *MockIEmployeeRepository_DeleteWithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 *gorm.DB
		if args[2] != nil {
			arg2 = args[2].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIEmployeeRepository_DeleteWithTx_Call) Return(err error) *MockIEmployeeRepository_DeleteWithTx_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIEmployeeRepository_DeleteWithTx_Call) RunAndReturn(run func(ctx context.Context, ID uuid.UUID, trx *gorm.DB) error) *MockIEmployeeRepository_DeleteWithTx_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type MockIEmployeeRepository
func (_mock *MockIEmployeeRepository) GetAll(ctx context.Context) ([]employee.Employee, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []employee.Employee
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]employee.Employee, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []employee.Employee); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]employee.Employee)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIEmployeeRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockIEmployeeRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIEmployeeRepository_Expecter) GetAll(ctx interface{}) *MockIEmployeeRepository_GetAll_Call {
	return &MockIEmployeeRepository_GetAll_Call{Call: _e.mock.On("GetAll", ctx)}
}

func (_c *MockIEmployeeRepository_GetAll_Call) Run(run func(ctx context.Context)) *MockIEmployeeRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIEmployeeRepository_GetAll_Call) Return(employees []employee.Employee, err error) *MockIEmployeeRepository_GetAll_Call {
	_c.Call.Return(employees, err)
	return _c
}

func (_c *MockIEmployeeRepository_GetAll_Call) RunAndReturn(run func(ctx context.Context) ([]employee.Employee, error)) *MockIEmployeeRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockIEmployeeRepository
func (_mock *MockIEmployeeRepository) GetByID(ctx context.Context, ID uuid.UUID) (employee.Employee, error) {
	ret := _mock.Called(ctx, ID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 employee.Employee
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (employee.Employee, error)); ok {
		return returnFunc(ctx, ID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) employee.Employee); ok {
		r0 = returnFunc(ctx, ID)
	} else {
		r0 = ret.Get(0).(employee.Employee)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, ID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIEmployeeRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockIEmployeeRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - ID uuid.UUID
func (_e *MockIEmployeeRepository_Expecter) GetByID(ctx interface{}, ID interface{}) *MockIEmployeeRepository_GetByID_Call {
	return &MockIEmployeeRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, ID)}
}

func (_c *MockIEmployeeRepository_GetByID_Call) Run(run func(ctx context.Context, ID uuid.UUID)) *MockIEmployeeRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIEmployeeRepository_GetByID_Call) Return(employee1 employee.Employee, err error) *MockIEmployeeRepository_GetByID_Call {
	_c.Call.Return(employee1, err)
	return _c
}

func (_c *MockIEmployeeRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, ID uuid.UUID) (employee.Employee, error)) *MockIEmployeeRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByIDLockTx provides a mock function for the type MockIEmployeeRepository
func (_mock *MockIEmployeeRepository) GetByIDLockTx(ctx context.Context, ID uuid.UUID, trx *gorm.DB) (employee.Employee, error) {
	ret := _mock.Called(ctx, ID, trx)

	if len(ret) == 0 {
		panic("no return value specified for GetByIDLockTx")
	}

	var r0 employee.Employee
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *gorm.DB) (employee.Employee, error)); ok {
		return returnFunc(ctx, ID, trx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *gorm.DB) employee.Employee); ok {
		r0 = returnFunc(ctx, ID, trx)
	} else {
		r0 = ret.Get(0).(employee.Employee)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, *gorm.DB) error); ok {
		r1 = returnFunc(ctx, ID, trx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIEmployeeRepository_GetByIDLockTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByIDLockTx'
type MockIEmployeeRepository_GetByIDLockTx_Call struct {
	*mock.Call
}

// GetByIDLockTx is a helper method to define mock.On call
//   - ctx context.Context
//   - ID uuid.UUID
//   - trx *gorm.DB
func (_e *MockIEmployeeRepository_Expecter) GetByIDLockTx(ctx interface{}, ID interface{}, trx interface{}) *MockIEmployeeRepository_GetByIDLockTx_Call {
	return &MockIEmployeeRepository_GetByIDLockTx_Call{Call: _e.mock.On("GetByIDLockTx", ctx, ID, trx)}
}

func (_c *MockIEmployeeRepository_GetByIDLockTx_Call) Run(run func(ctx context.Context, ID uuid.UUID, trx *gorm.DB)) *MockIEmployeeRepository_GetByIDLockTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 *gorm.DB
		if args[2] != nil {
			arg2 = args[2].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIEmployeeRepository_GetByIDLockTx_Call) Return(employee1 employee.Employee, err error) *MockIEmployeeRepository_GetByIDLockTx_Call {
	_c.Call.Return(employee1, err)
	return _c
}

func (_c *MockIEmployeeRepository_GetByIDLockTx_Call) RunAndReturn(run func(ctx context.Context, ID uuid.UUID, trx *gorm.DB) (employee.Employee, error)) *MockIEmployeeRepository_GetByIDLockTx_Call {
	_c.Call.Return(run)
	return _c
}

// GetByIDs provides a mock function for the type MockIEmployeeRepository
func (_mock *MockIEmployeeRepository) GetByIDs(ctx context.Context, IDs []uuid.UUID) ([]employee.Employee, error) {
	ret := _mock.Called(ctx, IDs)

	if len(ret) == 0 {
		panic("no return value specified for GetByIDs")
	}

	var r0 []employee.Employee
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) ([]employee.Employee, error)); ok {
		return returnFunc(ctx, IDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) []employee.Employee); ok {
		r0 = returnFunc(ctx, IDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]employee.Employee)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []uuid.UUID) error); ok {
		r1 = returnFunc(ctx, IDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIEmployeeRepository_GetByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByIDs'
type MockIEmployeeRepository_GetByIDs_Call struct {
	*mock.Call
}

// GetByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - IDs []uuid.UUID
func (_e *MockIEmployeeRepository_Expecter) GetByIDs(ctx interface{}, IDs interface{}) *MockIEmployeeRepository_GetByIDs_Call {
	return &MockIEmployeeRepository_GetByIDs_Call{Call: _e.mock.On("GetByIDs", ctx, IDs)}
}

func (_c *MockIEmployeeRepository_GetByIDs_Call) Run(run func(ctx context.Context, IDs []uuid.UUID)) *MockIEmployeeRepository_GetByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIEmployeeRepository_GetByIDs_Call) Return(employees []employee.Employee, err error) *MockIEmployeeRepository_GetByIDs_Call {
	_c.Call.Return(employees, err)
	return _c
}

func (_c *MockIEmployeeRepository_GetByIDs_Call) RunAndReturn(run func(ctx context.Context, IDs []uuid.UUID) ([]employee.Employee, error)) *MockIEmployeeRepository_GetByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// Pagination provides a mock function for the type MockIEmployeeRepository
func (_mock *MockIEmployeeRepository) Pagination(ctx context.Context, filter map[string]any, page int, limit int) (repository.Pagination[employee.Employee], error) {
	ret := _mock.Called(ctx, filter, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for Pagination")
	}

	var r0 repository.Pagination[employee.Employee]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[string]any, int, int) (repository.Pagination[employee.Employee], error)); ok {
		return returnFunc(ctx, filter, page, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[string]any, int, int) repository.Pagination[employee.Employee]); ok {
		r0 = returnFunc(ctx, filter, page, limit)
	} else {
		r0 = ret.Get(0).(repository.Pagination[employee.Employee])
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, map[string]any, int, int) error); ok {
		r1 = returnFunc(ctx, filter, page, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIEmployeeRepository_Pagination_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pagination'
type MockIEmployeeRepository_Pagination_Call struct {
	*mock.Call
}

// Pagination is a helper method to define mock.On call
//   - ctx context.Context
//   - filter map[string]any
//   - page int
//   - limit int
func (_e *MockIEmployeeRepository_Expecter) Pagination(ctx interface{}, filter interface{}, page interface{}, limit interface{}) *MockIEmployeeRepository_Pagination_Call {
	return &MockIEmployeeRepository_Pagination_Call{Call: _e.mock.On("Pagination", ctx, filter, page, limit)}
}

func (_c *MockIEmployeeRepository_Pagination_Call) Run(run func(ctx context.Context, filter map[string]any, page int, limit int)) *MockIEmployeeRepository_Pagination_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 map[string]any
		if args[1] != nil {
			arg1 = args[1].(map[string]any)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockIEmployeeRepository_Pagination_Call) Return(res repository.Pagination[employee.Employee], err error) *MockIEmployeeRepository_Pagination_Call {
	_c.Call.Return(res, err)
	return _c
}

func (_c *MockIEmployeeRepository_Pagination_Call) RunAndReturn(run func(ctx context.Context, filter map[string]any, page int, limit int) (repository.Pagination[employee.Employee], error)) *MockIEmployeeRepository_Pagination_Call {
	_c.Call.Return(run)
	return _c
}

// Rollback provides a mock function for the type MockIEmployeeRepository
func (_mock *MockIEmployeeRepository) Rollback(trx *gorm.DB) *gorm.DB {
	ret := _mock.Called(trx)

	if len(ret) == 0 {
		panic("no return value specified for Rollback")
	}

	var r0 *gorm.DB
	if returnFunc, ok := ret.Get(0).(func(*gorm.DB) *gorm.DB); ok {
		r0 = returnFunc(trx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}
	return r0
}

// MockIEmployeeRepository_Rollback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rollback'
type MockIEmployeeRepository_Rollback_Call struct {
	*mock.Call
}

// Rollback is a helper method to define mock.On call
//   - trx *gorm.DB
func (_e *MockIEmployeeRepository_Expecter) Rollback(trx interface{}) *MockIEmployeeRepository_Rollback_Call {
	return &MockIEmployeeRepository_Rollback_Call{Call: _e.mock.On("Rollback", trx)}
}

func (_c *MockIEmployeeRepository_Rollback_Call) Run(run func(trx *gorm.DB)) *MockIEmployeeRepository_Rollback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIEmployeeRepository_Rollback_Call) Return(dB *gorm.DB) *MockIEmployeeRepository_Rollback_Call {
	_c.Call.Return(dB)
	return _c
}

func (_c *MockIEmployeeRepository_Rollback_Call) RunAndReturn(run func(trx *gorm.DB) *gorm.DB) *MockIEmployeeRepository_Rollback_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockIEmployeeRepository
func (_mock *MockIEmployeeRepository) Update(ctx context.Context, ID uuid.UUID, model employee.Employee) (employee.Employee, error) {
	ret := _mock.Called(ctx, ID, model)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 employee.Employee
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, employee.Employee) (employee.Employee, error)); ok {
		return returnFunc(ctx, ID, model)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, employee.Employee) employee.Employee); ok {
		r0 = returnFunc(ctx, ID, model)
	} else {
		r0 = ret.Get(0).(employee.Employee)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, employee.Employee) error); ok {
		r1 = returnFunc(ctx, ID, model)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIEmployeeRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockIEmployeeRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - ID uuid.UUID
//   - model employee.Employee
func (_e *MockIEmployeeRepository_Expecter) Update(ctx interface{}, ID interface{}, model interface{}) *MockIEmployeeRepository_Update_Call {
	return &MockIEmployeeRepository_Update_Call{Call: _e.mock.On("Update", ctx, ID, model)}
}

func (_c *MockIEmployeeRepository_Update_Call) Run(run func(ctx context.Context, ID uuid.UUID, model employee.Employee)) *MockIEmployeeRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 employee.Employee
		if args[2] != nil {
			arg2 = args[2].(employee.Employee)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIEmployeeRepository_Update_Call) Return(employee1 employee.Employee, err error) *MockIEmployeeRepository_Update_Call {
	_c.Call.Return(employee1, err)
	return _c
}

func (_c *MockIEmployeeRepository_Update_Call) RunAndReturn(run func(ctx context.Context, ID uuid.UUID, model employee.Employee) (employee.Employee, error)) *MockIEmployeeRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateBulk provides a mock function for the type MockIEmployeeRepository
func (_mock *MockIEmployeeRepository) UpdateBulk(ctx context.Context, IDs []uuid.UUID, payload map[string]any) error {
	ret := _mock.Called(ctx, IDs, payload)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBulk")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID, map[string]any) error); ok {
		r0 = returnFunc(ctx, IDs, payload)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIEmployeeRepository_UpdateBulk_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateBulk'
type MockIEmployeeRepository_UpdateBulk_Call struct {
	*mock.Call
}

// UpdateBulk is a helper method to define mock.On call
//   - ctx context.Context
//   - IDs []uuid.UUID
//   - payload map[string]any
func (_e *MockIEmployeeRepository_Expecter) UpdateBulk(ctx interface{}, IDs interface{}, payload interface{}) *MockIEmployeeRepository_UpdateBulk_Call {
	return &MockIEmployeeRepository_UpdateBulk_Call{Call: _e.mock.On("UpdateBulk", ctx, IDs, payload)}
}

func (_c *MockIEmployeeRepository_UpdateBulk_Call) Run(run func(ctx context.Context, IDs []uuid.UUID, payload map[string]any)) *MockIEmployeeRepository_UpdateBulk_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		var arg2 map[string]any
		if args[2] != nil {
			arg2 = args[2].(map[string]any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIEmployeeRepository_UpdateBulk_Call) Return(err error) *MockIEmployeeRepository_UpdateBulk_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIEmployeeRepository_UpdateBulk_Call) RunAndReturn(run func(ctx context.Context, IDs []uuid.UUID, payload map[string]any) error) *MockIEmployeeRepository_UpdateBulk_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateBulkWithTx provides a mock function for the type MockIEmployeeRepository
func (_mock *MockIEmployeeRepository) UpdateBulkWithTx(ctx context.Context, IDs []uuid.UUID, payload map[string]any, trx *gorm.DB) error {
	ret := _mock.Called(ctx, IDs, payload, trx)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBulkWithTx")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID, map[string]any, *gorm.DB) error); ok {
		r0 = returnFunc(ctx, IDs, payload, trx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIEmployeeRepository_UpdateBulkWithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateBulkWithTx'
type MockIEmployeeRepository_UpdateBulkWithTx_Call struct {
	*mock.Call
}

// UpdateBulkWithTx is a helper method to define mock.On call
//   - ctx context.Context
//   - IDs []uuid.UUID
//   - payload map[string]any
//   - trx *gorm.DB
func (_e *MockIEmployeeRepository_Expecter) UpdateBulkWithTx(ctx interface{}, IDs interface{}, payload interface{}, trx interface{}) *MockIEmployeeRepository_UpdateBulkWithTx_Call {
	return &MockIEmployeeRepository_UpdateBulkWithTx_Call{Call: _e.mock.On("UpdateBulkWithTx", ctx, IDs, payload, trx)}
}

func (_c *MockIEmployeeRepository_UpdateBulkWithTx_Call) Run(run func(ctx context.Context, IDs []uuid.UUID, payload map[string]any, trx *gorm.DB)) *MockIEmployeeRepository_UpdateBulkWithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		var arg2 map[string]any
		if args[2] != nil {
			arg2 = args[2].(map[string]any)
		}
		var arg3 *gorm.DB
		if args[3] != nil {
			arg3 = args[3].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockIEmployeeRepository_UpdateBulkWithTx_Call) Return(err error) *MockIEmployeeRepository_UpdateBulkWithTx_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIEmployeeRepository_UpdateBulkWithTx_Call) RunAndReturn(run func(ctx context.Context, IDs []uuid.UUID, payload map[string]any, trx *gorm.DB) error) *MockIEmployeeRepository_UpdateBulkWithTx_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateWithMap provides a mock function for the type MockIEmployeeRepository
func (_mock *MockIEmployeeRepository) UpdateWithMap(ctx context.Context, ID uuid.UUID, payload map[string]any) (employee.Employee, error) {
	ret := _mock.Called(ctx, ID, payload)

	if len(ret) == 0 {
		panic("no return value specified for UpdateWithMap")
	}

	var r0 employee.Employee
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, map[string]any) (employee.Employee, error)); ok {
		return returnFunc(ctx, ID, payload)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, map[string]any) employee.Employee); ok {
		r0 = returnFunc(ctx, ID, payload)
	} else {
		r0 = ret.Get(0).(employee.Employee)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, map[string]any) error); ok {
		r1 = returnFunc(ctx, ID, payload)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIEmployeeRepository_UpdateWithMap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateWithMap'
type MockIEmployeeRepository_UpdateWithMap_Call struct {
	*mock.Call
}

// UpdateWithMap is a helper method to define mock.On call
//   - ctx context.Context
//   - ID uuid.UUID
//   - payload map[string]any
func (_e *MockIEmployeeRepository_Expecter) UpdateWithMap(ctx interface{}, ID interface{}, payload interface{}) *MockIEmployeeRepository_UpdateWithMap_Call {
	return &MockIEmployeeRepository_UpdateWithMap_Call{Call: _e.mock.On("UpdateWithMap", ctx, ID, payload)}
}

func (_c *MockIEmployeeRepository_UpdateWithMap_Call) Run(run func(ctx context.Context, ID uuid.UUID, payload map[string]any)) *MockIEmployeeRepository_UpdateWithMap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 map[string]any
		if args[2] != nil {
			arg2 = args[2].(map[string]any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIEmployeeRepository_UpdateWithMap_Call) Return(employee1 employee.Employee, err error) *MockIEmployeeRepository_UpdateWithMap_Call {
	_c.Call.Return(employee1, err)
	return _c
}

func (_c *MockIEmployeeRepository_UpdateWithMap_Call) RunAndReturn(run func(ctx context.Context, ID uuid.UUID, payload map[string]any) (employee.Employee, error)) *MockIEmployeeRepository_UpdateWithMap_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateWithMapTx provides a mock function for the type MockIEmployeeRepository
func (_mock *MockIEmployeeRepository) UpdateWithMapTx(ctx context.Context, ID uuid.UUID, payload map[string]any, trx *gorm.DB) (employee.Employee, error) {
	ret := _mock.Called(ctx, ID, payload, trx)

	if len(ret) == 0 {
		panic("no return value specified for UpdateWithMapTx")
	}

	var r0 employee.Employee
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, map[string]any, *gorm.DB) (employee.Employee, error)); ok {
		return returnFunc(ctx, ID, payload, trx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, map[string]any, *gorm.DB) employee.Employee); ok {
		r0 = returnFunc(ctx, ID, payload, trx)
	} else {
		r0 = ret.Get(0).(employee.Employee)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, map[string]any, *gorm.DB) error); ok {
		r1 = returnFunc(ctx, ID, payload, trx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIEmployeeRepository_UpdateWithMapTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateWithMapTx'
type MockIEmployeeRepository_UpdateWithMapTx_Call struct {
	*mock.Call
}

// UpdateWithMapTx is a helper method to define mock.On call
//   - ctx context.Context
//   - ID uuid.UUID
//   - payload map[string]any
//   - trx *gorm.DB
func (_e *MockIEmployeeRepository_Expecter) UpdateWithMapTx(ctx interface{}, ID interface{}, payload interface{}, trx interface{}) *MockIEmployeeRepository_UpdateWithMapTx_Call {
	return &MockIEmployeeRepository_UpdateWithMapTx_Call{Call: _e.mock.On("UpdateWithMapTx", ctx, ID, payload, trx)}
}

func (_c *MockIEmployeeRepository_UpdateWithMapTx_Call) Run(run func(ctx context.Context, ID uuid.UUID, payload map[string]any, trx *gorm.DB)) *MockIEmployeeRepository_UpdateWithMapTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 map[string]any
		if args[2] != nil {
			arg2 = args[2].(map[string]any)
		}
		var arg3 *gorm.DB
		if args[3] != nil {
			arg3 = args[3].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockIEmployeeRepository_UpdateWithMapTx_Call) Return(employee1 employee.Employee, err error) *MockIEmployeeRepository_UpdateWithMapTx_Call {
	_c.Call.Return(employee1, err)
	return _c
}

func (_c *MockIEmployeeRepository_UpdateWithMapTx_Call) RunAndReturn(run func(ctx context.Context, ID uuid.UUID, payload map[string]any, trx *gorm.DB) (employee.Employee, error)) *MockIEmployeeRepository_UpdateWithMapTx_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateWithTx provides a mock function for the type MockIEmployeeRepository
func (_mock *MockIEmployeeRepository) UpdateWithTx(ctx context.Context, ID uuid.UUID, model employee.Employee, trx *gorm.DB) (employee.Employee, error) {
	ret := _mock.Called(ctx, ID, model, trx)

	if len(ret) == 0 {
		panic("no return value specified for UpdateWithTx")
	}

	var r0 employee.Employee
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, employee.Employee, *gorm.DB) (employee.Employee, error)); ok {
		return returnFunc(ctx, ID, model, trx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, employee.Employee, *gorm.DB) employee.Employee); ok {
		r0 = returnFunc(ctx, ID, model, trx)
	} else {
		r0 = ret.Get(0).(employee.Employee)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, employee.Employee, *gorm.DB) error); ok {
		r1 = returnFunc(ctx, ID, model, trx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIEmployeeRepository_UpdateWithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateWithTx'
type MockIEmployeeRepository_UpdateWithTx_Call struct {
	*mock.Call
}

// UpdateWithTx is a helper method to define mock.On call
//   - ctx context.Context
//   - ID uuid.UUID
//   - model employee.Employee
//   - trx *gorm.DB
func (_e *MockIEmployeeRepository_Expecter) UpdateWithTx(ctx interface{}, ID interface{}, model interface{}, trx interface{}) *MockIEmployeeRepository_UpdateWithTx_Call {
	return &MockIEmployeeRepository_UpdateWithTx_Call{Call: _e.mock.On("UpdateWithTx", ctx, ID, model, trx)}
}

func (_c *MockIEmployeeRepository_UpdateWithTx_Call) Run(run func(ctx context.Context, ID uuid.UUID, model employee.Employee, trx *gorm.DB)) *MockIEmployeeRepository_UpdateWithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 employee.Employee
		if args[2] != nil {
			arg2 = args[2].(employee.Employee)
		}
		var arg3 *gorm.DB
		if args[3] != nil {
			arg3 = args[3].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockIEmployeeRepository_UpdateWithTx_Call) Return(employee1 employee.Employee, err error) *MockIEmployeeRepository_UpdateWithTx_Call {
	_c.Call.Return(employee1, err)
	return _c
}

func (_c *MockIEmployeeRepository_UpdateWithTx_Call) RunAndReturn(run func(ctx context.Context, ID uuid.UUID, model employee.Employee, trx *gorm.DB) (employee.Employee, error)) *MockIEmployeeRepository_UpdateWithTx_Call {
	_c.Call.Return(run)
	return _c
}
