// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package loan

import (
	"context"

	"github.com/BagusAK95/amarta_test/internal/domain/common/repository"
	"github.com/BagusAK95/amarta_test/internal/domain/loan"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
	"gorm.io/gorm"
)

// NewMockILoanRepository creates a new instance of MockILoanRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockILoanRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockILoanRepository {
	mock := &MockILoanRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockILoanRepository is an autogenerated mock type for the ILoanRepository type
type MockILoanRepository struct {
	mock.Mock
}

type MockILoanRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockILoanRepository) EXPECT() *MockILoanRepository_Expecter {
	return &MockILoanRepository_Expecter{mock: &_m.Mock}
}

// BeginTransaction provides a mock function for the type MockILoanRepository
func (_mock *MockILoanRepository) BeginTransaction(ctx context.Context) *gorm.DB {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for BeginTransaction")
	}

	var r0 *gorm.DB
	if returnFunc, ok := ret.Get(0).(func(context.Context) *gorm.DB); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}
	return r0
}

// MockILoanRepository_BeginTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginTransaction'
type MockILoanRepository_BeginTransaction_Call struct {
	*mock.Call
}

// BeginTransaction is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockILoanRepository_Expecter) BeginTransaction(ctx interface{}) *MockILoanRepository_BeginTransaction_Call {
	return &MockILoanRepository_BeginTransaction_Call{Call: _e.mock.On("BeginTransaction", ctx)}
}

func (_c *MockILoanRepository_BeginTransaction_Call) Run(run func(ctx context.Context)) *MockILoanRepository_BeginTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockILoanRepository_BeginTransaction_Call) Return(dB *gorm.DB) *MockILoanRepository_BeginTransaction_Call {
	_c.Call.Return(dB)
	return _c
}

func (_c *MockILoanRepository_BeginTransaction_Call) RunAndReturn(run func(ctx context.Context) *gorm.DB) *MockILoanRepository_BeginTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// Commit provides a mock function for the type MockILoanRepository
func (_mock *MockILoanRepository) Commit(trx *gorm.DB) *gorm.DB {
	ret := _mock.Called(trx)

	if len(ret) == 0 {
		panic("no return value specified for Commit")
	}

	var r0 *gorm.DB
	if returnFunc, ok := ret.Get(0).(func(*gorm.DB) *gorm.DB); ok {
		r0 = returnFunc(trx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}
	return r0
}

// MockILoanRepository_Commit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Commit'
type MockILoanRepository_Commit_Call struct {
	*mock.Call
}

// Commit is a helper method to define mock.On call
//   - trx *gorm.DB
func (_e *MockILoanRepository_Expecter) Commit(trx interface{}) *MockILoanRepository_Commit_Call {
	return &MockILoanRepository_Commit_Call{Call: _e.mock.On("Commit", trx)}
}

func (_c *MockILoanRepository_Commit_Call) Run(run func(trx *gorm.DB)) *MockILoanRepository_Commit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockILoanRepository_Commit_Call) Return(dB *gorm.DB) *MockILoanRepository_Commit_Call {
	_c.Call.Return(dB)
	return _c
}

func (_c *MockILoanRepository_Commit_Call) RunAndReturn(run func(trx *gorm.DB) *gorm.DB) *MockILoanRepository_Commit_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockILoanRepository
func (_mock *MockILoanRepository) Create(ctx context.Context, model loan.Loan) (loan.Loan, error) {
	ret := _mock.Called(ctx, model)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 loan.Loan
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, loan.Loan) (loan.Loan, error)); ok {
		return returnFunc(ctx, model)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, loan.Loan) loan.Loan); ok {
		r0 = returnFunc(ctx, model)
	} else {
		r0 = ret.Get(0).(loan.Loan)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, loan.Loan) error); ok {
		r1 = returnFunc(ctx, model)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockILoanRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockILoanRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - model loan.Loan
func (_e *MockILoanRepository_Expecter) Create(ctx interface{}, model interface{}) *MockILoanRepository_Create_Call {
	return &MockILoanRepository_Create_Call{Call: _e.mock.On("Create", ctx, model)}
}

func (_c *MockILoanRepository_Create_Call) Run(run func(ctx context.Context, model loan.Loan)) *MockILoanRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 loan.Loan
		if args[1] != nil {
			arg1 = args[1].(loan.Loan)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockILoanRepository_Create_Call) Return(loan1 loan.Loan, err error) *MockILoanRepository_Create_Call {
	_c.Call.Return(loan1, err)
	return _c
}

func (_c *MockILoanRepository_Create_Call) RunAndReturn(run func(ctx context.Context, model loan.Loan) (loan.Loan, error)) *MockILoanRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateBulk provides a mock function for the type MockILoanRepository
func (_mock *MockILoanRepository) CreateBulk(ctx context.Context, models []loan.Loan) error {
	ret := _mock.Called(ctx, models)

	if len(ret) == 0 {
		panic("no return value specified for CreateBulk")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []loan.Loan) error); ok {
		r0 = returnFunc(ctx, models)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockILoanRepository_CreateBulk_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBulk'
type MockILoanRepository_CreateBulk_Call struct {
	*mock.Call
}

// CreateBulk is a helper method to define mock.On call
//   - ctx context.Context
//   - models []loan.Loan
func (_e *MockILoanRepository_Expecter) CreateBulk(ctx interface{}, models interface{}) *MockILoanRepository_CreateBulk_Call {
	return &MockILoanRepository_CreateBulk_Call{Call: _e.mock.On("CreateBulk", ctx, models)}
}

func (_c *MockILoanRepository_CreateBulk_Call) Run(run func(ctx context.Context, models []loan.Loan)) *MockILoanRepository_CreateBulk_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []loan.Loan
		if args[1] != nil {
			arg1 = args[1].([]loan.Loan)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockILoanRepository_CreateBulk_Call) Return(err error) *MockILoanRepository_CreateBulk_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockILoanRepository_CreateBulk_Call) RunAndReturn(run func(ctx context.Context, models []loan.Loan) error) *MockILoanRepository_CreateBulk_Call {
	_c.Call.Return(run)
	return _c
}

// CreateBulkAndReturnWithTx provides a mock function for the type MockILoanRepository
func (_mock *MockILoanRepository) CreateBulkAndReturnWithTx(ctx context.Context, models []loan.Loan, trx *gorm.DB) ([]loan.Loan, error) {
	ret := _mock.Called(ctx, models, trx)

	if len(ret) == 0 {
		panic("no return value specified for CreateBulkAndReturnWithTx")
	}

	var r0 []loan.Loan
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []loan.Loan, *gorm.DB) ([]loan.Loan, error)); ok {
		return returnFunc(ctx, models, trx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []loan.Loan, *gorm.DB) []loan.Loan); ok {
		r0 = returnFunc(ctx, models, trx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]loan.Loan)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []loan.Loan, *gorm.DB) error); ok {
		r1 = returnFunc(ctx, models, trx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockILoanRepository_CreateBulkAndReturnWithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBulkAndReturnWithTx'
type MockILoanRepository_CreateBulkAndReturnWithTx_Call struct {
	*mock.Call
}

// CreateBulkAndReturnWithTx is a helper method to define mock.On call
//   - ctx context.Context
//   - models []loan.Loan
//   - trx *gorm.DB
func (_e *MockILoanRepository_Expecter) CreateBulkAndReturnWithTx(ctx interface{}, models interface{}, trx interface{}) *MockILoanRepository_CreateBulkAndReturnWithTx_Call {
	return &MockILoanRepository_CreateBulkAndReturnWithTx_Call{Call: _e.mock.On("CreateBulkAndReturnWithTx", ctx, models, trx)}
}

func (_c *MockILoanRepository_CreateBulkAndReturnWithTx_Call) Run(run func(ctx context.Context, models []loan.Loan, trx *gorm.DB)) *MockILoanRepository_CreateBulkAndReturnWithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []loan.Loan
		if args[1] != nil {
			arg1 = args[1].([]loan.Loan)
		}
		var arg2 *gorm.DB
		if args[2] != nil {
			arg2 = args[2].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockILoanRepository_CreateBulkAndReturnWithTx_Call) Return(loans []loan.Loan, err error) *MockILoanRepository_CreateBulkAndReturnWithTx_Call {
	_c.Call.Return(loans, err)
	return _c
}

func (_c *MockILoanRepository_CreateBulkAndReturnWithTx_Call) RunAndReturn(run func(ctx context.Context, models []loan.Loan, trx *gorm.DB) ([]loan.Loan, error)) *MockILoanRepository_CreateBulkAndReturnWithTx_Call {
	_c.Call.Return(run)
	return _c
}

// CreateBulkWithTx provides a mock function for the type MockILoanRepository
func (_mock *MockILoanRepository) CreateBulkWithTx(ctx context.Context, models []loan.Loan, trx *gorm.DB) error {
	ret := _mock.Called(ctx, models, trx)

	if len(ret) == 0 {
		panic("no return value specified for CreateBulkWithTx")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []loan.Loan, *gorm.DB) error); ok {
		r0 = returnFunc(ctx, models, trx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockILoanRepository_CreateBulkWithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBulkWithTx'
type MockILoanRepository_CreateBulkWithTx_Call struct {
	*mock.Call
}

// CreateBulkWithTx is a helper method to define mock.On call
//   - ctx context.Context
//   - models []loan.Loan
//   - trx *gorm.DB
func (_e *MockILoanRepository_Expecter) CreateBulkWithTx(ctx interface{}, models interface{}, trx interface{}) *MockILoanRepository_CreateBulkWithTx_Call {
	return &MockILoanRepository_CreateBulkWithTx_Call{Call: _e.mock.On("CreateBulkWithTx", ctx, models, trx)}
}

func (_c *MockILoanRepository_CreateBulkWithTx_Call) Run(run func(ctx context.Context, models []loan.Loan, trx *gorm.DB)) *MockILoanRepository_CreateBulkWithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []loan.Loan
		if args[1] != nil {
			arg1 = args[1].([]loan.Loan)
		}
		var arg2 *gorm.DB
		if args[2] != nil {
			arg2 = args[2].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockILoanRepository_CreateBulkWithTx_Call) Return(err error) *MockILoanRepository_CreateBulkWithTx_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockILoanRepository_CreateBulkWithTx_Call) RunAndReturn(run func(ctx context.Context, models []loan.Loan, trx *gorm.DB) error) *MockILoanRepository_CreateBulkWithTx_Call {
	_c.Call.Return(run)
	return _c
}

// CreateWithTx provides a mock function for the type MockILoanRepository
func (_mock *MockILoanRepository) CreateWithTx(ctx context.Context, model loan.Loan, trx *gorm.DB) (loan.Loan, error) {
	ret := _mock.Called(ctx, model, trx)

	if len(ret) == 0 {
		panic("no return value specified for CreateWithTx")
	}

	var r0 loan.Loan
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, loan.Loan, *gorm.DB) (loan.Loan, error)); ok {
		return returnFunc(ctx, model, trx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, loan.Loan, *gorm.DB) loan.Loan); ok {
		r0 = returnFunc(ctx, model, trx)
	} else {
		r0 = ret.Get(0).(loan.Loan)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, loan.Loan, *gorm.DB) error); ok {
		r1 = returnFunc(ctx, model, trx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockILoanRepository_CreateWithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWithTx'
type MockILoanRepository_CreateWithTx_Call struct {
	*mock.Call
}

// CreateWithTx is a helper method to define mock.On call
//   - ctx context.Context
//   - model loan.Loan
//   - trx *gorm.DB
func (_e *MockILoanRepository_Expecter) CreateWithTx(ctx interface{}, model interface{}, trx interface{}) *MockILoanRepository_CreateWithTx_Call {
	return &MockILoanRepository_CreateWithTx_Call{Call: _e.mock.On("CreateWithTx", ctx, model, trx)}
}

func (_c *MockILoanRepository_CreateWithTx_Call) Run(run func(ctx context.Context, model loan.Loan, trx *gorm.DB)) *MockILoanRepository_CreateWithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 loan.Loan
		if args[1] != nil {
			arg1 = args[1].(loan.Loan)
		}
		var arg2 *gorm.DB
		if args[2] != nil {
			arg2 = args[2].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockILoanRepository_CreateWithTx_Call) Return(loan1 loan.Loan, err error) *MockILoanRepository_CreateWithTx_Call {
	_c.Call.Return(loan1, err)
	return _c
}

func (_c *MockILoanRepository_CreateWithTx_Call) RunAndReturn(run func(ctx context.Context, model loan.Loan, trx *gorm.DB) (loan.Loan, error)) *MockILoanRepository_CreateWithTx_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockILoanRepository
func (_mock *MockILoanRepository) Delete(ctx context.Context, ID uuid.UUID) error {
	ret := _mock.Called(ctx, ID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, ID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockILoanRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockILoanRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - ID uuid.UUID
func (_e *MockILoanRepository_Expecter) Delete(ctx interface{}, ID interface{}) *MockILoanRepository_Delete_Call {
	return &MockILoanRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, ID)}
}

func (_c *MockILoanRepository_Delete_Call) Run(run func(ctx context.Context, ID uuid.UUID)) *MockILoanRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockILoanRepository_Delete_Call) Return(err error) *MockILoanRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockILoanRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, ID uuid.UUID) error) *MockILoanRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteBulk provides a mock function for the type MockILoanRepository
func (_mock *MockILoanRepository) DeleteBulk(ctx context.Context, IDs []uuid.UUID) error {
	ret := _mock.Called(ctx, IDs)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBulk")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) error); ok {
		r0 = returnFunc(ctx, IDs)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockILoanRepository_DeleteBulk_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBulk'
type MockILoanRepository_DeleteBulk_Call struct {
	*mock.Call
}

// DeleteBulk is a helper method to define mock.On call
//   - ctx context.Context
//   - IDs []uuid.UUID
func (_e *MockILoanRepository_Expecter) DeleteBulk(ctx interface{}, IDs interface{}) *MockILoanRepository_DeleteBulk_Call {
	return &MockILoanRepository_DeleteBulk_Call{Call: _e.mock.On("DeleteBulk", ctx, IDs)}
}

func (_c *MockILoanRepository_DeleteBulk_Call) Run(run func(ctx context.Context, IDs []uuid.UUID)) *MockILoanRepository_DeleteBulk_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockILoanRepository_DeleteBulk_Call) Return(err error) *MockILoanRepository_DeleteBulk_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockILoanRepository_DeleteBulk_Call) RunAndReturn(run func(ctx context.Context, IDs []uuid.UUID) error) *MockILoanRepository_DeleteBulk_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteBulkWithTx provides a mock function for the type MockILoanRepository
func (_mock *MockILoanRepository) DeleteBulkWithTx(ctx context.Context, IDs []uuid.UUID, trx *gorm.DB) error {
	ret := _mock.Called(ctx, IDs, trx)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBulkWithTx")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID, *gorm.DB) error); ok {
		r0 = returnFunc(ctx, IDs, trx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockILoanRepository_DeleteBulkWithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBulkWithTx'
type MockILoanRepository_DeleteBulkWithTx_Call struct {
	*mock.Call
}

// DeleteBulkWithTx is a helper method to define mock.On call
//   - ctx context.Context
//   - IDs []uuid.UUID
//   - trx *gorm.DB
func (_e *MockILoanRepository_Expecter) DeleteBulkWithTx(ctx interface{}, IDs interface{}, trx interface{}) *MockILoanRepository_DeleteBulkWithTx_Call {
	return &MockILoanRepository_DeleteBulkWithTx_Call{Call: _e.mock.On("DeleteBulkWithTx", ctx, IDs, trx)}
}

func (_c *MockILoanRepository_DeleteBulkWithTx_Call) Run(run func(ctx context.Context, IDs []uuid.UUID, trx *gorm.DB)) *MockILoanRepository_DeleteBulkWithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		var arg2 *gorm.DB
		if args[2] != nil {
			arg2 = args[2].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockILoanRepository_DeleteBulkWithTx_Call) Return(err error) *MockILoanRepository_DeleteBulkWithTx_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockILoanRepository_DeleteBulkWithTx_Call) RunAndReturn(run func(ctx context.Context, IDs []uuid.UUID, trx *gorm.DB) error) *MockILoanRepository_DeleteBulkWithTx_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteWithTx provides a mock function for the type MockILoanRepository
func (_mock *MockILoanRepository) DeleteWithTx(ctx context.Context, ID uuid.UUID, trx *gorm.DB) error {
	ret := _mock.Called(ctx, ID, trx)

	if len(ret) == 0 {
		panic("no return value specified for DeleteWithTx")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *gorm.DB) error); ok {
		r0 = returnFunc(ctx, ID, trx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockILoanRepository_DeleteWithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteWithTx'
type MockILoanRepository_DeleteWithTx_Call struct {
	*mock.Call
}

// DeleteWithTx is a helper method to define mock.On call
//   - ctx context.Context
//   - ID uuid.UUID
//   - trx *gorm.DB
func (_e *MockILoanRepository_Expecter) DeleteWithTx(ctx interface{}, ID interface{}, trx interface{}) *MockILoanRepository_DeleteWithTx_Call {
	return &MockILoanRepository_DeleteWithTx_Call{Call: _e.mock.On("DeleteWithTx", ctx, ID, trx)}
}

func (_c *MockILoanRepository_DeleteWithTx_Call) Run(run func(ctx context.Context, ID uuid.UUID, trx *gorm.DB)) *MockILoanRepository_DeleteWithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 *gorm.DB
		if args[2] != nil {
			arg2 = args[2].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockILoanRepository_DeleteWithTx_Call) Return(err error) *MockILoanRepository_DeleteWithTx_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockILoanRepository_DeleteWithTx_Call) RunAndReturn(run func(ctx context.Context, ID uuid.UUID, trx *gorm.DB) error) *MockILoanRepository_DeleteWithTx_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type MockILoanRepository
func (_mock *MockILoanRepository) GetAll(ctx context.Context) ([]loan.Loan, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []loan.Loan
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]loan.Loan, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []loan.Loan); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]loan.Loan)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockILoanRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockILoanRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockILoanRepository_Expecter) GetAll(ctx interface{}) *MockILoanRepository_GetAll_Call {
	return &MockILoanRepository_GetAll_Call{Call: _e.mock.On("GetAll", ctx)}
}

func (_c *MockILoanRepository_GetAll_Call) Run(run func(ctx context.Context)) *MockILoanRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockILoanRepository_GetAll_Call) Return(loans []loan.Loan, err error) *MockILoanRepository_GetAll_Call {
	_c.Call.Return(loans, err)
	return _c
}

func (_c *MockILoanRepository_GetAll_Call) RunAndReturn(run func(ctx context.Context) ([]loan.Loan, error)) *MockILoanRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockILoanRepository
func (_mock *MockILoanRepository) GetByID(ctx context.Context, ID uuid.UUID) (loan.Loan, error) {
	ret := _mock.Called(ctx, ID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 loan.Loan
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (loan.Loan, error)); ok {
		return returnFunc(ctx, ID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) loan.Loan); ok {
		r0 = returnFunc(ctx, ID)
	} else {
		r0 = ret.Get(0).(loan.Loan)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, ID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockILoanRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockILoanRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - ID uuid.UUID
func (_e *MockILoanRepository_Expecter) GetByID(ctx interface{}, ID interface{}) *MockILoanRepository_GetByID_Call {
	return &MockILoanRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, ID)}
}

func (_c *MockILoanRepository_GetByID_Call) Run(run func(ctx context.Context, ID uuid.UUID)) *MockILoanRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockILoanRepository_GetByID_Call) Return(loan1 loan.Loan, err error) *MockILoanRepository_GetByID_Call {
	_c.Call.Return(loan1, err)
	return _c
}

func (_c *MockILoanRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, ID uuid.UUID) (loan.Loan, error)) *MockILoanRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByIDLockTx provides a mock function for the type MockILoanRepository
func (_mock *MockILoanRepository) GetByIDLockTx(ctx context.Context, ID uuid.UUID, trx *gorm.DB) (loan.Loan, error) {
	ret := _mock.Called(ctx, ID, trx)

	if len(ret) == 0 {
		panic("no return value specified for GetByIDLockTx")
	}

	var r0 loan.Loan
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *gorm.DB) (loan.Loan, error)); ok {
		return returnFunc(ctx, ID, trx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *gorm.DB) loan.Loan); ok {
		r0 = returnFunc(ctx, ID, trx)
	} else {
		r0 = ret.Get(0).(loan.Loan)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, *gorm.DB) error); ok {
		r1 = returnFunc(ctx, ID, trx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockILoanRepository_GetByIDLockTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByIDLockTx'
type MockILoanRepository_GetByIDLockTx_Call struct {
	*mock.Call
}

// GetByIDLockTx is a helper method to define mock.On call
//   - ctx context.Context
//   - ID uuid.UUID
//   - trx *gorm.DB
func (_e *MockILoanRepository_Expecter) GetByIDLockTx(ctx interface{}, ID interface{}, trx interface{}) *MockILoanRepository_GetByIDLockTx_Call {
	return &MockILoanRepository_GetByIDLockTx_Call{Call: _e.mock.On("GetByIDLockTx", ctx, ID, trx)}
}

func (_c *MockILoanRepository_GetByIDLockTx_Call) Run(run func(ctx context.Context, ID uuid.UUID, trx *gorm.DB)) *MockILoanRepository_GetByIDLockTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 *gorm.DB
		if args[2] != nil {
			arg2 = args[2].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockILoanRepository_GetByIDLockTx_Call) Return(loan1 loan.Loan, err error) *MockILoanRepository_GetByIDLockTx_Call {
	_c.Call.Return(loan1, err)
	return _c
}

func (_c *MockILoanRepository_GetByIDLockTx_Call) RunAndReturn(run func(ctx context.Context, ID uuid.UUID, trx *gorm.DB) (loan.Loan, error)) *MockILoanRepository_GetByIDLockTx_Call {
	_c.Call.Return(run)
	return _c
}

// GetByIDs provides a mock function for the type MockILoanRepository
func (_mock *MockILoanRepository) GetByIDs(ctx context.Context, IDs []uuid.UUID) ([]loan.Loan, error) {
	ret := _mock.Called(ctx, IDs)

	if len(ret) == 0 {
		panic("no return value specified for GetByIDs")
	}

	var r0 []loan.Loan
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) ([]loan.Loan, error)); ok {
		return returnFunc(ctx, IDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) []loan.Loan); ok {
		r0 = returnFunc(ctx, IDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]loan.Loan)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []uuid.UUID) error); ok {
		r1 = returnFunc(ctx, IDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockILoanRepository_GetByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByIDs'
type MockILoanRepository_GetByIDs_Call struct {
	*mock.Call
}

// GetByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - IDs []uuid.UUID
func (_e *MockILoanRepository_Expecter) GetByIDs(ctx interface{}, IDs interface{}) *MockILoanRepository_GetByIDs_Call {
	return &MockILoanRepository_GetByIDs_Call{Call: _e.mock.On("GetByIDs", ctx, IDs)}
}

func (_c *MockILoanRepository_GetByIDs_Call) Run(run func(ctx context.Context, IDs []uuid.UUID)) *MockILoanRepository_GetByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockILoanRepository_GetByIDs_Call) Return(loans []loan.Loan, err error) *MockILoanRepository_GetByIDs_Call {
	_c.Call.Return(loans, err)
	return _c
}

func (_c *MockILoanRepository_GetByIDs_Call) RunAndReturn(run func(ctx context.Context, IDs []uuid.UUID) ([]loan.Loan, error)) *MockILoanRepository_GetByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// Pagination provides a mock function for the type MockILoanRepository
func (_mock *MockILoanRepository) Pagination(ctx context.Context, filter map[string]any, page int, limit int) (repository.Pagination[loan.Loan], error) {
	ret := _mock.Called(ctx, filter, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for Pagination")
	}

	var r0 repository.Pagination[loan.Loan]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[string]any, int, int) (repository.Pagination[loan.Loan], error)); ok {
		return returnFunc(ctx, filter, page, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[string]any, int, int) repository.Pagination[loan.Loan]); ok {
		r0 = returnFunc(ctx, filter, page, limit)
	} else {
		r0 = ret.Get(0).(repository.Pagination[loan.Loan])
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, map[string]any, int, int) error); ok {
		r1 = returnFunc(ctx, filter, page, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockILoanRepository_Pagination_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pagination'
type MockILoanRepository_Pagination_Call struct {
	*mock.Call
}

// Pagination is a helper method to define mock.On call
//   - ctx context.Context
//   - filter map[string]any
//   - page int
//   - limit int
func (_e *MockILoanRepository_Expecter) Pagination(ctx interface{}, filter interface{}, page interface{}, limit interface{}) *MockILoanRepository_Pagination_Call {
	return &MockILoanRepository_Pagination_Call{Call: _e.mock.On("Pagination", ctx, filter, page, limit)}
}

func (_c *MockILoanRepository_Pagination_Call) Run(run func(ctx context.Context, filter map[string]any, page int, limit int)) *MockILoanRepository_Pagination_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 map[string]any
		if args[1] != nil {
			arg1 = args[1].(map[string]any)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockILoanRepository_Pagination_Call) Return(res repository.Pagination[loan.Loan], err error) *MockILoanRepository_Pagination_Call {
	_c.Call.Return(res, err)
	return _c
}

func (_c *MockILoanRepository_Pagination_Call) RunAndReturn(run func(ctx context.Context, filter map[string]any, page int, limit int) (repository.Pagination[loan.Loan], error)) *MockILoanRepository_Pagination_Call {
	_c.Call.Return(run)
	return _c
}

// Rollback provides a mock function for the type MockILoanRepository
func (_mock *MockILoanRepository) Rollback(trx *gorm.DB) *gorm.DB {
	ret := _mock.Called(trx)

	if len(ret) == 0 {
		panic("no return value specified for Rollback")
	}

	var r0 *gorm.DB
	if returnFunc, ok := ret.Get(0).(func(*gorm.DB) *gorm.DB); ok {
		r0 = returnFunc(trx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}
	return r0
}

// MockILoanRepository_Rollback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rollback'
type MockILoanRepository_Rollback_Call struct {
	*mock.Call
}

// Rollback is a helper method to define mock.On call
//   - trx *gorm.DB
func (_e *MockILoanRepository_Expecter) Rollback(trx interface{}) *MockILoanRepository_Rollback_Call {
	return &MockILoanRepository_Rollback_Call{Call: _e.mock.On("Rollback", trx)}
}

func (_c *MockILoanRepository_Rollback_Call) Run(run func(trx *gorm.DB)) *MockILoanRepository_Rollback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockILoanRepository_Rollback_Call) Return(dB *gorm.DB) *MockILoanRepository_Rollback_Call {
	_c.Call.Return(dB)
	return _c
}

func (_c *MockILoanRepository_Rollback_Call) RunAndReturn(run func(trx *gorm.DB) *gorm.DB) *MockILoanRepository_Rollback_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockILoanRepository
func (_mock *MockILoanRepository) Update(ctx context.Context, ID uuid.UUID, model loan.Loan) (loan.Loan, error) {
	ret := _mock.Called(ctx, ID, model)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 loan.Loan
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, loan.Loan) (loan.Loan, error)); ok {
		return returnFunc(ctx, ID, model)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, loan.Loan) loan.Loan); ok {
		r0 = returnFunc(ctx, ID, model)
	} else {
		r0 = ret.Get(0).(loan.Loan)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, loan.Loan) error); ok {
		r1 = returnFunc(ctx, ID, model)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockILoanRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockILoanRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - ID uuid.UUID
//   - model loan.Loan
func (_e *MockILoanRepository_Expecter) Update(ctx interface{}, ID interface{}, model interface{}) *MockILoanRepository_Update_Call {
	return &MockILoanRepository_Update_Call{Call: _e.mock.On("Update", ctx, ID, model)}
}

func (_c *MockILoanRepository_Update_Call) Run(run func(ctx context.Context, ID uuid.UUID, model loan.Loan)) *MockILoanRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 loan.Loan
		if args[2] != nil {
			arg2 = args[2].(loan.Loan)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockILoanRepository_Update_Call) Return(loan1 loan.Loan, err error) *MockILoanRepository_Update_Call {
	_c.Call.Return(loan1, err)
	return _c
}

func (_c *MockILoanRepository_Update_Call) RunAndReturn(run func(ctx context.Context, ID uuid.UUID, model loan.Loan) (loan.Loan, error)) *MockILoanRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateBulk provides a mock function for the type MockILoanRepository
func (_mock *MockILoanRepository) UpdateBulk(ctx context.Context, IDs []uuid.UUID, payload map[string]any) error {
	ret := _mock.Called(ctx, IDs, payload)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBulk")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID, map[string]any) error); ok {
		r0 = returnFunc(ctx, IDs, payload)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockILoanRepository_UpdateBulk_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateBulk'
type MockILoanRepository_UpdateBulk_Call struct {
	*mock.Call
}

// UpdateBulk is a helper method to define mock.On call
//   - ctx context.Context
//   - IDs []uuid.UUID
//   - payload map[string]any
func (_e *MockILoanRepository_Expecter) UpdateBulk(ctx interface{}, IDs interface{}, payload interface{}) *MockILoanRepository_UpdateBulk_Call {
	return &MockILoanRepository_UpdateBulk_Call{Call: _e.mock.On("UpdateBulk", ctx, IDs, payload)}
}

func (_c *MockILoanRepository_UpdateBulk_Call) Run(run func(ctx context.Context, IDs []uuid.UUID, payload map[string]any)) *MockILoanRepository_UpdateBulk_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		var arg2 map[string]any
		if args[2] != nil {
			arg2 = args[2].(map[string]any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockILoanRepository_UpdateBulk_Call) Return(err error) *MockILoanRepository_UpdateBulk_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockILoanRepository_UpdateBulk_Call) RunAndReturn(run func(ctx context.Context, IDs []uuid.UUID, payload map[string]any) error) *MockILoanRepository_UpdateBulk_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateBulkWithTx provides a mock function for the type MockILoanRepository
func (_mock *MockILoanRepository) UpdateBulkWithTx(ctx context.Context, IDs []uuid.UUID, payload map[string]any, trx *gorm.DB) error {
	ret := _mock.Called(ctx, IDs, payload, trx)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBulkWithTx")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID, map[string]any, *gorm.DB) error); ok {
		r0 = returnFunc(ctx, IDs, payload, trx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockILoanRepository_UpdateBulkWithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateBulkWithTx'
type MockILoanRepository_UpdateBulkWithTx_Call struct {
	*mock.Call
}

// UpdateBulkWithTx is a helper method to define mock.On call
//   - ctx context.Context
//   - IDs []uuid.UUID
//   - payload map[string]any
//   - trx *gorm.DB
func (_e *MockILoanRepository_Expecter) UpdateBulkWithTx(ctx interface{}, IDs interface{}, payload interface{}, trx interface{}) *MockILoanRepository_UpdateBulkWithTx_Call {
	return &MockILoanRepository_UpdateBulkWithTx_Call{Call: _e.mock.On("UpdateBulkWithTx", ctx, IDs, payload, trx)}
}

func (_c *MockILoanRepository_UpdateBulkWithTx_Call) Run(run func(ctx context.Context, IDs []uuid.UUID, payload map[string]any, trx *gorm.DB)) *MockILoanRepository_UpdateBulkWithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		var arg2 map[string]any
		if args[2] != nil {
			arg2 = args[2].(map[string]any)
		}
		var arg3 *gorm.DB
		if args[3] != nil {
			arg3 = args[3].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockILoanRepository_UpdateBulkWithTx_Call) Return(err error) *MockILoanRepository_UpdateBulkWithTx_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockILoanRepository_UpdateBulkWithTx_Call) RunAndReturn(run func(ctx context.Context, IDs []uuid.UUID, payload map[string]any, trx *gorm.DB) error) *MockILoanRepository_UpdateBulkWithTx_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateWithMap provides a mock function for the type MockILoanRepository
func (_mock *MockILoanRepository) UpdateWithMap(ctx context.Context, ID uuid.UUID, payload map[string]any) (loan.Loan, error) {
	ret := _mock.Called(ctx, ID, payload)

	if len(ret) == 0 {
		panic("no return value specified for UpdateWithMap")
	}

	var r0 loan.Loan
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, map[string]any) (loan.Loan, error)); ok {
		return returnFunc(ctx, ID, payload)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, map[string]any) loan.Loan); ok {
		r0 = returnFunc(ctx, ID, payload)
	} else {
		r0 = ret.Get(0).(loan.Loan)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, map[string]any) error); ok {
		r1 = returnFunc(ctx, ID, payload)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockILoanRepository_UpdateWithMap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateWithMap'
type MockILoanRepository_UpdateWithMap_Call struct {
	*mock.Call
}

// UpdateWithMap is a helper method to define mock.On call
//   - ctx context.Context
//   - ID uuid.UUID
//   - payload map[string]any
func (_e *MockILoanRepository_Expecter) UpdateWithMap(ctx interface{}, ID interface{}, payload interface{}) *MockILoanRepository_UpdateWithMap_Call {
	return &MockILoanRepository_UpdateWithMap_Call{Call: _e.mock.On("UpdateWithMap", ctx, ID, payload)}
}

func (_c *MockILoanRepository_UpdateWithMap_Call) Run(run func(ctx context.Context, ID uuid.UUID, payload map[string]any)) *MockILoanRepository_UpdateWithMap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 map[string]any
		if args[2] != nil {
			arg2 = args[2].(map[string]any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockILoanRepository_UpdateWithMap_Call) Return(loan1 loan.Loan, err error) *MockILoanRepository_UpdateWithMap_Call {
	_c.Call.Return(loan1, err)
	return _c
}

func (_c *MockILoanRepository_UpdateWithMap_Call) RunAndReturn(run func(ctx context.Context, ID uuid.UUID, payload map[string]any) (loan.Loan, error)) *MockILoanRepository_UpdateWithMap_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateWithMapTx provides a mock function for the type MockILoanRepository
func (_mock *MockILoanRepository) UpdateWithMapTx(ctx context.Context, ID uuid.UUID, payload map[string]any, trx *gorm.DB) (loan.Loan, error) {
	ret := _mock.Called(ctx, ID, payload, trx)

	if len(ret) == 0 {
		panic("no return value specified for UpdateWithMapTx")
	}

	var r0 loan.Loan
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, map[string]any, *gorm.DB) (loan.Loan, error)); ok {
		return returnFunc(ctx, ID, payload, trx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, map[string]any, *gorm.DB) loan.Loan); ok {
		r0 = returnFunc(ctx, ID, payload, trx)
	} else {
		r0 = ret.Get(0).(loan.Loan)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, map[string]any, *gorm.DB) error); ok {
		r1 = returnFunc(ctx, ID, payload, trx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockILoanRepository_UpdateWithMapTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateWithMapTx'
type MockILoanRepository_UpdateWithMapTx_Call struct {
	*mock.Call
}

// UpdateWithMapTx is a helper method to define mock.On call
//   - ctx context.Context
//   - ID uuid.UUID
//   - payload map[string]any
//   - trx *gorm.DB
func (_e *MockILoanRepository_Expecter) UpdateWithMapTx(ctx interface{}, ID interface{}, payload interface{}, trx interface{}) *MockILoanRepository_UpdateWithMapTx_Call {
	return &MockILoanRepository_UpdateWithMapTx_Call{Call: _e.mock.On("UpdateWithMapTx", ctx, ID, payload, trx)}
}

func (_c *MockILoanRepository_UpdateWithMapTx_Call) Run(run func(ctx context.Context, ID uuid.UUID, payload map[string]any, trx *gorm.DB)) *MockILoanRepository_UpdateWithMapTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 map[string]any
		if args[2] != nil {
			arg2 = args[2].(map[string]any)
		}
		var arg3 *gorm.DB
		if args[3] != nil {
			arg3 = args[3].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockILoanRepository_UpdateWithMapTx_Call) Return(loan1 loan.Loan, err error) *MockILoanRepository_UpdateWithMapTx_Call {
	_c.Call.Return(loan1, err)
	return _c
}

func (_c *MockILoanRepository_UpdateWithMapTx_Call) RunAndReturn(run func(ctx context.Context, ID uuid.UUID, payload map[string]any, trx *gorm.DB) (loan.Loan, error)) *MockILoanRepository_UpdateWithMapTx_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateWithTx provides a mock function for the type MockILoanRepository
func (_mock *MockILoanRepository) UpdateWithTx(ctx context.Context, ID uuid.UUID, model loan.Loan, trx *gorm.DB) (loan.Loan, error) {
	ret := _mock.Called(ctx, ID, model, trx)

	if len(ret) == 0 {
		panic("no return value specified for UpdateWithTx")
	}

	var r0 loan.Loan
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, loan.Loan, *gorm.DB) (loan.Loan, error)); ok {
		return returnFunc(ctx, ID, model, trx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, loan.Loan, *gorm.DB) loan.Loan); ok {
		r0 = returnFunc(ctx, ID, model, trx)
	} else {
		r0 = ret.Get(0).(loan.Loan)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, loan.Loan, *gorm.DB) error); ok {
		r1 = returnFunc(ctx, ID, model, trx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockILoanRepository_UpdateWithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateWithTx'
type MockILoanRepository_UpdateWithTx_Call struct {
	*mock.Call
}

// UpdateWithTx is a helper method to define mock.On call
//   - ctx context.Context
//   - ID uuid.UUID
//   - model loan.Loan
//   - trx *gorm.DB
func (_e *MockILoanRepository_Expecter) UpdateWithTx(ctx interface{}, ID interface{}, model interface{}, trx interface{}) *MockILoanRepository_UpdateWithTx_Call {
	return &MockILoanRepository_UpdateWithTx_Call{Call: _e.mock.On("UpdateWithTx", ctx, ID, model, trx)}
}

func (_c *MockILoanRepository_UpdateWithTx_Call) Run(run func(ctx context.Context, ID uuid.UUID, model loan.Loan, trx *gorm.DB)) *MockILoanRepository_UpdateWithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 loan.Loan
		if args[2] != nil {
			arg2 = args[2].(loan.Loan)
		}
		var arg3 *gorm.DB
		if args[3] != nil {
			arg3 = args[3].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockILoanRepository_UpdateWithTx_Call) Return(loan1 loan.Loan, err error) *MockILoanRepository_UpdateWithTx_Call {
	_c.Call.Return(loan1, err)
	return _c
}

func (_c *MockILoanRepository_UpdateWithTx_Call) RunAndReturn(run func(ctx context.Context, ID uuid.UUID, model loan.Loan, trx *gorm.DB) (loan.Loan, error)) *MockILoanRepository_UpdateWithTx_Call {
	_c.Call.Return(run)
	return _c
}
