// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package investment

import (
	"context"

	"github.com/BagusAK95/amarta_test/internal/domain/common/repository"
	"github.com/BagusAK95/amarta_test/internal/domain/investment"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
	"gorm.io/gorm"
)

// NewMockIInvestmentRepository creates a new instance of MockIInvestmentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIInvestmentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIInvestmentRepository {
	mock := &MockIInvestmentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIInvestmentRepository is an autogenerated mock type for the IInvestmentRepository type
type MockIInvestmentRepository struct {
	mock.Mock
}

type MockIInvestmentRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIInvestmentRepository) EXPECT() *MockIInvestmentRepository_Expecter {
	return &MockIInvestmentRepository_Expecter{mock: &_m.Mock}
}

// BeginTransaction provides a mock function for the type MockIInvestmentRepository
func (_mock *MockIInvestmentRepository) BeginTransaction(ctx context.Context) *gorm.DB {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for BeginTransaction")
	}

	var r0 *gorm.DB
	if returnFunc, ok := ret.Get(0).(func(context.Context) *gorm.DB); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}
	return r0
}

// MockIInvestmentRepository_BeginTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginTransaction'
type MockIInvestmentRepository_BeginTransaction_Call struct {
	*mock.Call
}

// BeginTransaction is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIInvestmentRepository_Expecter) BeginTransaction(ctx interface{}) *MockIInvestmentRepository_BeginTransaction_Call {
	return &MockIInvestmentRepository_BeginTransaction_Call{Call: _e.mock.On("BeginTransaction", ctx)}
}

func (_c *MockIInvestmentRepository_BeginTransaction_Call) Run(run func(ctx context.Context)) *MockIInvestmentRepository_BeginTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIInvestmentRepository_BeginTransaction_Call) Return(dB *gorm.DB) *MockIInvestmentRepository_BeginTransaction_Call {
	_c.Call.Return(dB)
	return _c
}

func (_c *MockIInvestmentRepository_BeginTransaction_Call) RunAndReturn(run func(ctx context.Context) *gorm.DB) *MockIInvestmentRepository_BeginTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// Commit provides a mock function for the type MockIInvestmentRepository
func (_mock *MockIInvestmentRepository) Commit(trx *gorm.DB) *gorm.DB {
	ret := _mock.Called(trx)

	if len(ret) == 0 {
		panic("no return value specified for Commit")
	}

	var r0 *gorm.DB
	if returnFunc, ok := ret.Get(0).(func(*gorm.DB) *gorm.DB); ok {
		r0 = returnFunc(trx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}
	return r0
}

// MockIInvestmentRepository_Commit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Commit'
type MockIInvestmentRepository_Commit_Call struct {
	*mock.Call
}

// Commit is a helper method to define mock.On call
//   - trx *gorm.DB
func (_e *MockIInvestmentRepository_Expecter) Commit(trx interface{}) *MockIInvestmentRepository_Commit_Call {
	return &MockIInvestmentRepository_Commit_Call{Call: _e.mock.On("Commit", trx)}
}

func (_c *MockIInvestmentRepository_Commit_Call) Run(run func(trx *gorm.DB)) *MockIInvestmentRepository_Commit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIInvestmentRepository_Commit_Call) Return(dB *gorm.DB) *MockIInvestmentRepository_Commit_Call {
	_c.Call.Return(dB)
	return _c
}

func (_c *MockIInvestmentRepository_Commit_Call) RunAndReturn(run func(trx *gorm.DB) *gorm.DB) *MockIInvestmentRepository_Commit_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockIInvestmentRepository
func (_mock *MockIInvestmentRepository) Create(ctx context.Context, model investment.Investment) (investment.Investment, error) {
	ret := _mock.Called(ctx, model)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 investment.Investment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, investment.Investment) (investment.Investment, error)); ok {
		return returnFunc(ctx, model)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, investment.Investment) investment.Investment); ok {
		r0 = returnFunc(ctx, model)
	} else {
		r0 = ret.Get(0).(investment.Investment)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, investment.Investment) error); ok {
		r1 = returnFunc(ctx, model)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIInvestmentRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIInvestmentRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - model investment.Investment
func (_e *MockIInvestmentRepository_Expecter) Create(ctx interface{}, model interface{}) *MockIInvestmentRepository_Create_Call {
	return &MockIInvestmentRepository_Create_Call{Call: _e.mock.On("Create", ctx, model)}
}

func (_c *MockIInvestmentRepository_Create_Call) Run(run func(ctx context.Context, model investment.Investment)) *MockIInvestmentRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 investment.Investment
		if args[1] != nil {
			arg1 = args[1].(investment.Investment)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIInvestmentRepository_Create_Call) Return(investment1 investment.Investment, err error) *MockIInvestmentRepository_Create_Call {
	_c.Call.Return(investment1, err)
	return _c
}

func (_c *MockIInvestmentRepository_Create_Call) RunAndReturn(run func(ctx context.Context, model investment.Investment) (investment.Investment, error)) *MockIInvestmentRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateBulk provides a mock function for the type MockIInvestmentRepository
func (_mock *MockIInvestmentRepository) CreateBulk(ctx context.Context, models []investment.Investment) error {
	ret := _mock.Called(ctx, models)

	if len(ret) == 0 {
		panic("no return value specified for CreateBulk")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []investment.Investment) error); ok {
		r0 = returnFunc(ctx, models)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIInvestmentRepository_CreateBulk_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBulk'
type MockIInvestmentRepository_CreateBulk_Call struct {
	*mock.Call
}

// CreateBulk is a helper method to define mock.On call
//   - ctx context.Context
//   - models []investment.Investment
func (_e *MockIInvestmentRepository_Expecter) CreateBulk(ctx interface{}, models interface{}) *MockIInvestmentRepository_CreateBulk_Call {
	return &MockIInvestmentRepository_CreateBulk_Call{Call: _e.mock.On("CreateBulk", ctx, models)}
}

func (_c *MockIInvestmentRepository_CreateBulk_Call) Run(run func(ctx context.Context, models []investment.Investment)) *MockIInvestmentRepository_CreateBulk_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []investment.Investment
		if args[1] != nil {
			arg1 = args[1].([]investment.Investment)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIInvestmentRepository_CreateBulk_Call) Return(err error) *MockIInvestmentRepository_CreateBulk_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIInvestmentRepository_CreateBulk_Call) RunAndReturn(run func(ctx context.Context, models []investment.Investment) error) *MockIInvestmentRepository_CreateBulk_Call {
	_c.Call.Return(run)
	return _c
}

// CreateBulkAndReturnWithTx provides a mock function for the type MockIInvestmentRepository
func (_mock *MockIInvestmentRepository) CreateBulkAndReturnWithTx(ctx context.Context, models []investment.Investment, trx *gorm.DB) ([]investment.Investment, error) {
	ret := _mock.Called(ctx, models, trx)

	if len(ret) == 0 {
		panic("no return value specified for CreateBulkAndReturnWithTx")
	}

	var r0 []investment.Investment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []investment.Investment, *gorm.DB) ([]investment.Investment, error)); ok {
		return returnFunc(ctx, models, trx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []investment.Investment, *gorm.DB) []investment.Investment); ok {
		r0 = returnFunc(ctx, models, trx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]investment.Investment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []investment.Investment, *gorm.DB) error); ok {
		r1 = returnFunc(ctx, models, trx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIInvestmentRepository_CreateBulkAndReturnWithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBulkAndReturnWithTx'
type MockIInvestmentRepository_CreateBulkAndReturnWithTx_Call struct {
	*mock.Call
}

// CreateBulkAndReturnWithTx is a helper method to define mock.On call
//   - ctx context.Context
//   - models []investment.Investment
//   - trx *gorm.DB
func (_e *MockIInvestmentRepository_Expecter) CreateBulkAndReturnWithTx(ctx interface{}, models interface{}, trx interface{}) *MockIInvestmentRepository_CreateBulkAndReturnWithTx_Call {
	return &MockIInvestmentRepository_CreateBulkAndReturnWithTx_Call{Call: _e.mock.On("CreateBulkAndReturnWithTx", ctx, models, trx)}
}

func (_c *MockIInvestmentRepository_CreateBulkAndReturnWithTx_Call) Run(run func(ctx context.Context, models []investment.Investment, trx *gorm.DB)) *MockIInvestmentRepository_CreateBulkAndReturnWithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []investment.Investment
		if args[1] != nil {
			arg1 = args[1].([]investment.Investment)
		}
		var arg2 *gorm.DB
		if args[2] != nil {
			arg2 = args[2].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIInvestmentRepository_CreateBulkAndReturnWithTx_Call) Return(investments []investment.Investment, err error) *MockIInvestmentRepository_CreateBulkAndReturnWithTx_Call {
	_c.Call.Return(investments, err)
	return _c
}

func (_c *MockIInvestmentRepository_CreateBulkAndReturnWithTx_Call) RunAndReturn(run func(ctx context.Context, models []investment.Investment, trx *gorm.DB) ([]investment.Investment, error)) *MockIInvestmentRepository_CreateBulkAndReturnWithTx_Call {
	_c.Call.Return(run)
	return _c
}

// CreateBulkWithTx provides a mock function for the type MockIInvestmentRepository
func (_mock *MockIInvestmentRepository) CreateBulkWithTx(ctx context.Context, models []investment.Investment, trx *gorm.DB) error {
	ret := _mock.Called(ctx, models, trx)

	if len(ret) == 0 {
		panic("no return value specified for CreateBulkWithTx")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []investment.Investment, *gorm.DB) error); ok {
		r0 = returnFunc(ctx, models, trx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIInvestmentRepository_CreateBulkWithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBulkWithTx'
type MockIInvestmentRepository_CreateBulkWithTx_Call struct {
	*mock.Call
}

// CreateBulkWithTx is a helper method to define mock.On call
//   - ctx context.Context
//   - models []investment.Investment
//   - trx *gorm.DB
func (_e *MockIInvestmentRepository_Expecter) CreateBulkWithTx(ctx interface{}, models interface{}, trx interface{}) *MockIInvestmentRepository_CreateBulkWithTx_Call {
	return &MockIInvestmentRepository_CreateBulkWithTx_Call{Call: _e.mock.On("CreateBulkWithTx", ctx, models, trx)}
}

func (_c *MockIInvestmentRepository_CreateBulkWithTx_Call) Run(run func(ctx context.Context, models []investment.Investment, trx *gorm.DB)) *MockIInvestmentRepository_CreateBulkWithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []investment.Investment
		if args[1] != nil {
			arg1 = args[1].([]investment.Investment)
		}
		var arg2 *gorm.DB
		if args[2] != nil {
			arg2 = args[2].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIInvestmentRepository_CreateBulkWithTx_Call) Return(err error) *MockIInvestmentRepository_CreateBulkWithTx_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIInvestmentRepository_CreateBulkWithTx_Call) RunAndReturn(run func(ctx context.Context, models []investment.Investment, trx *gorm.DB) error) *MockIInvestmentRepository_CreateBulkWithTx_Call {
	_c.Call.Return(run)
	return _c
}

// CreateWithTx provides a mock function for the type MockIInvestmentRepository
func (_mock *MockIInvestmentRepository) CreateWithTx(ctx context.Context, model investment.Investment, trx *gorm.DB) (investment.Investment, error) {
	ret := _mock.Called(ctx, model, trx)

	if len(ret) == 0 {
		panic("no return value specified for CreateWithTx")
	}

	var r0 investment.Investment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, investment.Investment, *gorm.DB) (investment.Investment, error)); ok {
		return returnFunc(ctx, model, trx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, investment.Investment, *gorm.DB) investment.Investment); ok {
		r0 = returnFunc(ctx, model, trx)
	} else {
		r0 = ret.Get(0).(investment.Investment)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, investment.Investment, *gorm.DB) error); ok {
		r1 = returnFunc(ctx, model, trx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIInvestmentRepository_CreateWithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWithTx'
type MockIInvestmentRepository_CreateWithTx_Call struct {
	*mock.Call
}

// CreateWithTx is a helper method to define mock.On call
//   - ctx context.Context
//   - model investment.Investment
//   - trx *gorm.DB
func (_e *MockIInvestmentRepository_Expecter) CreateWithTx(ctx interface{}, model interface{}, trx interface{}) *MockIInvestmentRepository_CreateWithTx_Call {
	return &MockIInvestmentRepository_CreateWithTx_Call{Call: _e.mock.On("CreateWithTx", ctx, model, trx)}
}

func (_c *MockIInvestmentRepository_CreateWithTx_Call) Run(run func(ctx context.Context, model investment.Investment, trx *gorm.DB)) *MockIInvestmentRepository_CreateWithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 investment.Investment
		if args[1] != nil {
			arg1 = args[1].(investment.Investment)
		}
		var arg2 *gorm.DB
		if args[2] != nil {
			arg2 = args[2].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIInvestmentRepository_CreateWithTx_Call) Return(investment1 investment.Investment, err error) *MockIInvestmentRepository_CreateWithTx_Call {
	_c.Call.Return(investment1, err)
	return _c
}

func (_c *MockIInvestmentRepository_CreateWithTx_Call) RunAndReturn(run func(ctx context.Context, model investment.Investment, trx *gorm.DB) (investment.Investment, error)) *MockIInvestmentRepository_CreateWithTx_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockIInvestmentRepository
func (_mock *MockIInvestmentRepository) Delete(ctx context.Context, ID uuid.UUID) error {
	ret := _mock.Called(ctx, ID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, ID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIInvestmentRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockIInvestmentRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - ID uuid.UUID
func (_e *MockIInvestmentRepository_Expecter) Delete(ctx interface{}, ID interface{}) *MockIInvestmentRepository_Delete_Call {
	return &MockIInvestmentRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, ID)}
}

func (_c *MockIInvestmentRepository_Delete_Call) Run(run func(ctx context.Context, ID uuid.UUID)) *MockIInvestmentRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIInvestmentRepository_Delete_Call) Return(err error) *MockIInvestmentRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIInvestmentRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, ID uuid.UUID) error) *MockIInvestmentRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteBulk provides a mock function for the type MockIInvestmentRepository
func (_mock *MockIInvestmentRepository) DeleteBulk(ctx context.Context, IDs []uuid.UUID) error {
	ret := _mock.Called(ctx, IDs)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBulk")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) error); ok {
		r0 = returnFunc(ctx, IDs)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIInvestmentRepository_DeleteBulk_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBulk'
type MockIInvestmentRepository_DeleteBulk_Call struct {
	*mock.Call
}

// DeleteBulk is a helper method to define mock.On call
//   - ctx context.Context
//   - IDs []uuid.UUID
func (_e *MockIInvestmentRepository_Expecter) DeleteBulk(ctx interface{}, IDs interface{}) *MockIInvestmentRepository_DeleteBulk_Call {
	return &MockIInvestmentRepository_DeleteBulk_Call{Call: _e.mock.On("DeleteBulk", ctx, IDs)}
}

func (_c *MockIInvestmentRepository_DeleteBulk_Call) Run(run func(ctx context.Context, IDs []uuid.UUID)) *MockIInvestmentRepository_DeleteBulk_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIInvestmentRepository_DeleteBulk_Call) Return(err error) *MockIInvestmentRepository_DeleteBulk_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIInvestmentRepository_DeleteBulk_Call) RunAndReturn(run func(ctx context.Context, IDs []uuid.UUID) error) *MockIInvestmentRepository_DeleteBulk_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteBulkWithTx provides a mock function for the type MockIInvestmentRepository
func (_mock *MockIInvestmentRepository) DeleteBulkWithTx(ctx context.Context, IDs []uuid.UUID, trx *gorm.DB) error {
	ret := _mock.Called(ctx, IDs, trx)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBulkWithTx")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID, *gorm.DB) error); ok {
		r0 = returnFunc(ctx, IDs, trx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIInvestmentRepository_DeleteBulkWithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBulkWithTx'
type MockIInvestmentRepository_DeleteBulkWithTx_Call struct {
	*mock.Call
}

// DeleteBulkWithTx is a helper method to define mock.On call
//   - ctx context.Context
//   - IDs []uuid.UUID
//   - trx *gorm.DB
func (_e *MockIInvestmentRepository_Expecter) DeleteBulkWithTx(ctx interface{}, IDs interface{}, trx interface{}) *MockIInvestmentRepository_DeleteBulkWithTx_Call {
	return &MockIInvestmentRepository_DeleteBulkWithTx_Call{Call: _e.mock.On("DeleteBulkWithTx", ctx, IDs, trx)}
}

func (_c *MockIInvestmentRepository_DeleteBulkWithTx_Call) Run(run func(ctx context.Context, IDs []uuid.UUID, trx *gorm.DB)) *MockIInvestmentRepository_DeleteBulkWithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		var arg2 *gorm.DB
		if args[2] != nil {
			arg2 = args[2].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIInvestmentRepository_DeleteBulkWithTx_Call) Return(err error) *MockIInvestmentRepository_DeleteBulkWithTx_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIInvestmentRepository_DeleteBulkWithTx_Call) RunAndReturn(run func(ctx context.Context, IDs []uuid.UUID, trx *gorm.DB) error) *MockIInvestmentRepository_DeleteBulkWithTx_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteWithTx provides a mock function for the type MockIInvestmentRepository
func (_mock *MockIInvestmentRepository) DeleteWithTx(ctx context.Context, ID uuid.UUID, trx *gorm.DB) error {
	ret := _mock.Called(ctx, ID, trx)

	if len(ret) == 0 {
		panic("no return value specified for DeleteWithTx")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *gorm.DB) error); ok {
		r0 = returnFunc(ctx, ID, trx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIInvestmentRepository_DeleteWithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteWithTx'
type MockIInvestmentRepository_DeleteWithTx_Call struct {
	*mock.Call
}

// DeleteWithTx is a helper method to define mock.On call
//   - ctx context.Context
//   - ID uuid.UUID
//   - trx *gorm.DB
func (_e *MockIInvestmentRepository_Expecter) DeleteWithTx(ctx interface{}, ID interface{}, trx interface{}) *MockIInvestmentRepository_DeleteWithTx_Call {
	return &MockIInvestmentRepository_DeleteWithTx_Call{Call: _e.mock.On("DeleteWithTx", ctx, ID, trx)}
}

func (_c *MockIInvestmentRepository_DeleteWithTx_Call) Run(run func(ctx context.Context, ID uuid.UUID, trx *gorm.DB)) *MockIInvestmentRepository_DeleteWithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 *gorm.DB
		if args[2] != nil {
			arg2 = args[2].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIInvestmentRepository_DeleteWithTx_Call) Return(err error) *MockIInvestmentRepository_DeleteWithTx_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIInvestmentRepository_DeleteWithTx_Call) RunAndReturn(run func(ctx context.Context, ID uuid.UUID, trx *gorm.DB) error) *MockIInvestmentRepository_DeleteWithTx_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type MockIInvestmentRepository
func (_mock *MockIInvestmentRepository) GetAll(ctx context.Context) ([]investment.Investment, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []investment.Investment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]investment.Investment, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []investment.Investment); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]investment.Investment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIInvestmentRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockIInvestmentRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIInvestmentRepository_Expecter) GetAll(ctx interface{}) *MockIInvestmentRepository_GetAll_Call {
	return &MockIInvestmentRepository_GetAll_Call{Call: _e.mock.On("GetAll", ctx)}
}

func (_c *MockIInvestmentRepository_GetAll_Call) Run(run func(ctx context.Context)) *MockIInvestmentRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIInvestmentRepository_GetAll_Call) Return(investments []investment.Investment, err error) *MockIInvestmentRepository_GetAll_Call {
	_c.Call.Return(investments, err)
	return _c
}

func (_c *MockIInvestmentRepository_GetAll_Call) RunAndReturn(run func(ctx context.Context) ([]investment.Investment, error)) *MockIInvestmentRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockIInvestmentRepository
func (_mock *MockIInvestmentRepository) GetByID(ctx context.Context, ID uuid.UUID) (investment.Investment, error) {
	ret := _mock.Called(ctx, ID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 investment.Investment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (investment.Investment, error)); ok {
		return returnFunc(ctx, ID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) investment.Investment); ok {
		r0 = returnFunc(ctx, ID)
	} else {
		r0 = ret.Get(0).(investment.Investment)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, ID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIInvestmentRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockIInvestmentRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - ID uuid.UUID
func (_e *MockIInvestmentRepository_Expecter) GetByID(ctx interface{}, ID interface{}) *MockIInvestmentRepository_GetByID_Call {
	return &MockIInvestmentRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, ID)}
}

func (_c *MockIInvestmentRepository_GetByID_Call) Run(run func(ctx context.Context, ID uuid.UUID)) *MockIInvestmentRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIInvestmentRepository_GetByID_Call) Return(investment1 investment.Investment, err error) *MockIInvestmentRepository_GetByID_Call {
	_c.Call.Return(investment1, err)
	return _c
}

func (_c *MockIInvestmentRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, ID uuid.UUID) (investment.Investment, error)) *MockIInvestmentRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByIDLockTx provides a mock function for the type MockIInvestmentRepository
func (_mock *MockIInvestmentRepository) GetByIDLockTx(ctx context.Context, ID uuid.UUID, trx *gorm.DB) (investment.Investment, error) {
	ret := _mock.Called(ctx, ID, trx)

	if len(ret) == 0 {
		panic("no return value specified for GetByIDLockTx")
	}

	var r0 investment.Investment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *gorm.DB) (investment.Investment, error)); ok {
		return returnFunc(ctx, ID, trx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *gorm.DB) investment.Investment); ok {
		r0 = returnFunc(ctx, ID, trx)
	} else {
		r0 = ret.Get(0).(investment.Investment)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, *gorm.DB) error); ok {
		r1 = returnFunc(ctx, ID, trx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIInvestmentRepository_GetByIDLockTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByIDLockTx'
type MockIInvestmentRepository_GetByIDLockTx_Call struct {
	*mock.Call
}

// GetByIDLockTx is a helper method to define mock.On call
//   - ctx context.Context
//   - ID uuid.UUID
//   - trx *gorm.DB
func (_e *MockIInvestmentRepository_Expecter) GetByIDLockTx(ctx interface{}, ID interface{}, trx interface{}) *MockIInvestmentRepository_GetByIDLockTx_Call {
	return &MockIInvestmentRepository_GetByIDLockTx_Call{Call: _e.mock.On("GetByIDLockTx", ctx, ID, trx)}
}

func (_c *MockIInvestmentRepository_GetByIDLockTx_Call) Run(run func(ctx context.Context, ID uuid.UUID, trx *gorm.DB)) *MockIInvestmentRepository_GetByIDLockTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 *gorm.DB
		if args[2] != nil {
			arg2 = args[2].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIInvestmentRepository_GetByIDLockTx_Call) Return(investment1 investment.Investment, err error) *MockIInvestmentRepository_GetByIDLockTx_Call {
	_c.Call.Return(investment1, err)
	return _c
}

func (_c *MockIInvestmentRepository_GetByIDLockTx_Call) RunAndReturn(run func(ctx context.Context, ID uuid.UUID, trx *gorm.DB) (investment.Investment, error)) *MockIInvestmentRepository_GetByIDLockTx_Call {
	_c.Call.Return(run)
	return _c
}

// GetByIDs provides a mock function for the type MockIInvestmentRepository
func (_mock *MockIInvestmentRepository) GetByIDs(ctx context.Context, IDs []uuid.UUID) ([]investment.Investment, error) {
	ret := _mock.Called(ctx, IDs)

	if len(ret) == 0 {
		panic("no return value specified for GetByIDs")
	}

	var r0 []investment.Investment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) ([]investment.Investment, error)); ok {
		return returnFunc(ctx, IDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) []investment.Investment); ok {
		r0 = returnFunc(ctx, IDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]investment.Investment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []uuid.UUID) error); ok {
		r1 = returnFunc(ctx, IDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIInvestmentRepository_GetByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByIDs'
type MockIInvestmentRepository_GetByIDs_Call struct {
	*mock.Call
}

// GetByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - IDs []uuid.UUID
func (_e *MockIInvestmentRepository_Expecter) GetByIDs(ctx interface{}, IDs interface{}) *MockIInvestmentRepository_GetByIDs_Call {
	return &MockIInvestmentRepository_GetByIDs_Call{Call: _e.mock.On("GetByIDs", ctx, IDs)}
}

func (_c *MockIInvestmentRepository_GetByIDs_Call) Run(run func(ctx context.Context, IDs []uuid.UUID)) *MockIInvestmentRepository_GetByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIInvestmentRepository_GetByIDs_Call) Return(investments []investment.Investment, err error) *MockIInvestmentRepository_GetByIDs_Call {
	_c.Call.Return(investments, err)
	return _c
}

func (_c *MockIInvestmentRepository_GetByIDs_Call) RunAndReturn(run func(ctx context.Context, IDs []uuid.UUID) ([]investment.Investment, error)) *MockIInvestmentRepository_GetByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// GetTotalInvestmentByLoanID provides a mock function for the type MockIInvestmentRepository
func (_mock *MockIInvestmentRepository) GetTotalInvestmentByLoanID(ctx context.Context, loanID uuid.UUID) (float64, error) {
	ret := _mock.Called(ctx, loanID)

	if len(ret) == 0 {
		panic("no return value specified for GetTotalInvestmentByLoanID")
	}

	var r0 float64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (float64, error)); ok {
		return returnFunc(ctx, loanID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) float64); ok {
		r0 = returnFunc(ctx, loanID)
	} else {
		r0 = ret.Get(0).(float64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, loanID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIInvestmentRepository_GetTotalInvestmentByLoanID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTotalInvestmentByLoanID'
type MockIInvestmentRepository_GetTotalInvestmentByLoanID_Call struct {
	*mock.Call
}

// GetTotalInvestmentByLoanID is a helper method to define mock.On call
//   - ctx context.Context
//   - loanID uuid.UUID
func (_e *MockIInvestmentRepository_Expecter) GetTotalInvestmentByLoanID(ctx interface{}, loanID interface{}) *MockIInvestmentRepository_GetTotalInvestmentByLoanID_Call {
	return &MockIInvestmentRepository_GetTotalInvestmentByLoanID_Call{Call: _e.mock.On("GetTotalInvestmentByLoanID", ctx, loanID)}
}

func (_c *MockIInvestmentRepository_GetTotalInvestmentByLoanID_Call) Run(run func(ctx context.Context, loanID uuid.UUID)) *MockIInvestmentRepository_GetTotalInvestmentByLoanID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIInvestmentRepository_GetTotalInvestmentByLoanID_Call) Return(f float64, err error) *MockIInvestmentRepository_GetTotalInvestmentByLoanID_Call {
	_c.Call.Return(f, err)
	return _c
}

func (_c *MockIInvestmentRepository_GetTotalInvestmentByLoanID_Call) RunAndReturn(run func(ctx context.Context, loanID uuid.UUID) (float64, error)) *MockIInvestmentRepository_GetTotalInvestmentByLoanID_Call {
	_c.Call.Return(run)
	return _c
}

// Pagination provides a mock function for the type MockIInvestmentRepository
func (_mock *MockIInvestmentRepository) Pagination(ctx context.Context, filter map[string]any, page int, limit int) (repository.Pagination[investment.Investment], error) {
	ret := _mock.Called(ctx, filter, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for Pagination")
	}

	var r0 repository.Pagination[investment.Investment]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[string]any, int, int) (repository.Pagination[investment.Investment], error)); ok {
		return returnFunc(ctx, filter, page, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[string]any, int, int) repository.Pagination[investment.Investment]); ok {
		r0 = returnFunc(ctx, filter, page, limit)
	} else {
		r0 = ret.Get(0).(repository.Pagination[investment.Investment])
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, map[string]any, int, int) error); ok {
		r1 = returnFunc(ctx, filter, page, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIInvestmentRepository_Pagination_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pagination'
type MockIInvestmentRepository_Pagination_Call struct {
	*mock.Call
}

// Pagination is a helper method to define mock.On call
//   - ctx context.Context
//   - filter map[string]any
//   - page int
//   - limit int
func (_e *MockIInvestmentRepository_Expecter) Pagination(ctx interface{}, filter interface{}, page interface{}, limit interface{}) *MockIInvestmentRepository_Pagination_Call {
	return &MockIInvestmentRepository_Pagination_Call{Call: _e.mock.On("Pagination", ctx, filter, page, limit)}
}

func (_c *MockIInvestmentRepository_Pagination_Call) Run(run func(ctx context.Context, filter map[string]any, page int, limit int)) *MockIInvestmentRepository_Pagination_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 map[string]any
		if args[1] != nil {
			arg1 = args[1].(map[string]any)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockIInvestmentRepository_Pagination_Call) Return(res repository.Pagination[investment.Investment], err error) *MockIInvestmentRepository_Pagination_Call {
	_c.Call.Return(res, err)
	return _c
}

func (_c *MockIInvestmentRepository_Pagination_Call) RunAndReturn(run func(ctx context.Context, filter map[string]any, page int, limit int) (repository.Pagination[investment.Investment], error)) *MockIInvestmentRepository_Pagination_Call {
	_c.Call.Return(run)
	return _c
}

// Rollback provides a mock function for the type MockIInvestmentRepository
func (_mock *MockIInvestmentRepository) Rollback(trx *gorm.DB) *gorm.DB {
	ret := _mock.Called(trx)

	if len(ret) == 0 {
		panic("no return value specified for Rollback")
	}

	var r0 *gorm.DB
	if returnFunc, ok := ret.Get(0).(func(*gorm.DB) *gorm.DB); ok {
		r0 = returnFunc(trx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}
	return r0
}

// MockIInvestmentRepository_Rollback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rollback'
type MockIInvestmentRepository_Rollback_Call struct {
	*mock.Call
}

// Rollback is a helper method to define mock.On call
//   - trx *gorm.DB
func (_e *MockIInvestmentRepository_Expecter) Rollback(trx interface{}) *MockIInvestmentRepository_Rollback_Call {
	return &MockIInvestmentRepository_Rollback_Call{Call: _e.mock.On("Rollback", trx)}
}

func (_c *MockIInvestmentRepository_Rollback_Call) Run(run func(trx *gorm.DB)) *MockIInvestmentRepository_Rollback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIInvestmentRepository_Rollback_Call) Return(dB *gorm.DB) *MockIInvestmentRepository_Rollback_Call {
	_c.Call.Return(dB)
	return _c
}

func (_c *MockIInvestmentRepository_Rollback_Call) RunAndReturn(run func(trx *gorm.DB) *gorm.DB) *MockIInvestmentRepository_Rollback_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockIInvestmentRepository
func (_mock *MockIInvestmentRepository) Update(ctx context.Context, ID uuid.UUID, model investment.Investment) (investment.Investment, error) {
	ret := _mock.Called(ctx, ID, model)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 investment.Investment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, investment.Investment) (investment.Investment, error)); ok {
		return returnFunc(ctx, ID, model)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, investment.Investment) investment.Investment); ok {
		r0 = returnFunc(ctx, ID, model)
	} else {
		r0 = ret.Get(0).(investment.Investment)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, investment.Investment) error); ok {
		r1 = returnFunc(ctx, ID, model)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIInvestmentRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockIInvestmentRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - ID uuid.UUID
//   - model investment.Investment
func (_e *MockIInvestmentRepository_Expecter) Update(ctx interface{}, ID interface{}, model interface{}) *MockIInvestmentRepository_Update_Call {
	return &MockIInvestmentRepository_Update_Call{Call: _e.mock.On("Update", ctx, ID, model)}
}

func (_c *MockIInvestmentRepository_Update_Call) Run(run func(ctx context.Context, ID uuid.UUID, model investment.Investment)) *MockIInvestmentRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 investment.Investment
		if args[2] != nil {
			arg2 = args[2].(investment.Investment)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIInvestmentRepository_Update_Call) Return(investment1 investment.Investment, err error) *MockIInvestmentRepository_Update_Call {
	_c.Call.Return(investment1, err)
	return _c
}

func (_c *MockIInvestmentRepository_Update_Call) RunAndReturn(run func(ctx context.Context, ID uuid.UUID, model investment.Investment) (investment.Investment, error)) *MockIInvestmentRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateBulk provides a mock function for the type MockIInvestmentRepository
func (_mock *MockIInvestmentRepository) UpdateBulk(ctx context.Context, IDs []uuid.UUID, payload map[string]any) error {
	ret := _mock.Called(ctx, IDs, payload)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBulk")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID, map[string]any) error); ok {
		r0 = returnFunc(ctx, IDs, payload)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIInvestmentRepository_UpdateBulk_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateBulk'
type MockIInvestmentRepository_UpdateBulk_Call struct {
	*mock.Call
}

// UpdateBulk is a helper method to define mock.On call
//   - ctx context.Context
//   - IDs []uuid.UUID
//   - payload map[string]any
func (_e *MockIInvestmentRepository_Expecter) UpdateBulk(ctx interface{}, IDs interface{}, payload interface{}) *MockIInvestmentRepository_UpdateBulk_Call {
	return &MockIInvestmentRepository_UpdateBulk_Call{Call: _e.mock.On("UpdateBulk", ctx, IDs, payload)}
}

func (_c *MockIInvestmentRepository_UpdateBulk_Call) Run(run func(ctx context.Context, IDs []uuid.UUID, payload map[string]any)) *MockIInvestmentRepository_UpdateBulk_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		var arg2 map[string]any
		if args[2] != nil {
			arg2 = args[2].(map[string]any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIInvestmentRepository_UpdateBulk_Call) Return(err error) *MockIInvestmentRepository_UpdateBulk_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIInvestmentRepository_UpdateBulk_Call) RunAndReturn(run func(ctx context.Context, IDs []uuid.UUID, payload map[string]any) error) *MockIInvestmentRepository_UpdateBulk_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateBulkWithTx provides a mock function for the type MockIInvestmentRepository
func (_mock *MockIInvestmentRepository) UpdateBulkWithTx(ctx context.Context, IDs []uuid.UUID, payload map[string]any, trx *gorm.DB) error {
	ret := _mock.Called(ctx, IDs, payload, trx)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBulkWithTx")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID, map[string]any, *gorm.DB) error); ok {
		r0 = returnFunc(ctx, IDs, payload, trx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIInvestmentRepository_UpdateBulkWithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateBulkWithTx'
type MockIInvestmentRepository_UpdateBulkWithTx_Call struct {
	*mock.Call
}

// UpdateBulkWithTx is a helper method to define mock.On call
//   - ctx context.Context
//   - IDs []uuid.UUID
//   - payload map[string]any
//   - trx *gorm.DB
func (_e *MockIInvestmentRepository_Expecter) UpdateBulkWithTx(ctx interface{}, IDs interface{}, payload interface{}, trx interface{}) *MockIInvestmentRepository_UpdateBulkWithTx_Call {
	return &MockIInvestmentRepository_UpdateBulkWithTx_Call{Call: _e.mock.On("UpdateBulkWithTx", ctx, IDs, payload, trx)}
}

func (_c *MockIInvestmentRepository_UpdateBulkWithTx_Call) Run(run func(ctx context.Context, IDs []uuid.UUID, payload map[string]any, trx *gorm.DB)) *MockIInvestmentRepository_UpdateBulkWithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		var arg2 map[string]any
		if args[2] != nil {
			arg2 = args[2].(map[string]any)
		}
		var arg3 *gorm.DB
		if args[3] != nil {
			arg3 = args[3].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockIInvestmentRepository_UpdateBulkWithTx_Call) Return(err error) *MockIInvestmentRepository_UpdateBulkWithTx_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIInvestmentRepository_UpdateBulkWithTx_Call) RunAndReturn(run func(ctx context.Context, IDs []uuid.UUID, payload map[string]any, trx *gorm.DB) error) *MockIInvestmentRepository_UpdateBulkWithTx_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateWithMap provides a mock function for the type MockIInvestmentRepository
func (_mock *MockIInvestmentRepository) UpdateWithMap(ctx context.Context, ID uuid.UUID, payload map[string]any) (investment.Investment, error) {
	ret := _mock.Called(ctx, ID, payload)

	if len(ret) == 0 {
		panic("no return value specified for UpdateWithMap")
	}

	var r0 investment.Investment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, map[string]any) (investment.Investment, error)); ok {
		return returnFunc(ctx, ID, payload)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, map[string]any) investment.Investment); ok {
		r0 = returnFunc(ctx, ID, payload)
	} else {
		r0 = ret.Get(0).(investment.Investment)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, map[string]any) error); ok {
		r1 = returnFunc(ctx, ID, payload)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIInvestmentRepository_UpdateWithMap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateWithMap'
type MockIInvestmentRepository_UpdateWithMap_Call struct {
	*mock.Call
}

// UpdateWithMap is a helper method to define mock.On call
//   - ctx context.Context
//   - ID uuid.UUID
//   - payload map[string]any
func (_e *MockIInvestmentRepository_Expecter) UpdateWithMap(ctx interface{}, ID interface{}, payload interface{}) *MockIInvestmentRepository_UpdateWithMap_Call {
	return &MockIInvestmentRepository_UpdateWithMap_Call{Call: _e.mock.On("UpdateWithMap", ctx, ID, payload)}
}

func (_c *MockIInvestmentRepository_UpdateWithMap_Call) Run(run func(ctx context.Context, ID uuid.UUID, payload map[string]any)) *MockIInvestmentRepository_UpdateWithMap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 map[string]any
		if args[2] != nil {
			arg2 = args[2].(map[string]any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIInvestmentRepository_UpdateWithMap_Call) Return(investment1 investment.Investment, err error) *MockIInvestmentRepository_UpdateWithMap_Call {
	_c.Call.Return(investment1, err)
	return _c
}

func (_c *MockIInvestmentRepository_UpdateWithMap_Call) RunAndReturn(run func(ctx context.Context, ID uuid.UUID, payload map[string]any) (investment.Investment, error)) *MockIInvestmentRepository_UpdateWithMap_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateWithMapTx provides a mock function for the type MockIInvestmentRepository
func (_mock *MockIInvestmentRepository) UpdateWithMapTx(ctx context.Context, ID uuid.UUID, payload map[string]any, trx *gorm.DB) (investment.Investment, error) {
	ret := _mock.Called(ctx, ID, payload, trx)

	if len(ret) == 0 {
		panic("no return value specified for UpdateWithMapTx")
	}

	var r0 investment.Investment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, map[string]any, *gorm.DB) (investment.Investment, error)); ok {
		return returnFunc(ctx, ID, payload, trx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, map[string]any, *gorm.DB) investment.Investment); ok {
		r0 = returnFunc(ctx, ID, payload, trx)
	} else {
		r0 = ret.Get(0).(investment.Investment)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, map[string]any, *gorm.DB) error); ok {
		r1 = returnFunc(ctx, ID, payload, trx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIInvestmentRepository_UpdateWithMapTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateWithMapTx'
type MockIInvestmentRepository_UpdateWithMapTx_Call struct {
	*mock.Call
}

// UpdateWithMapTx is a helper method to define mock.On call
//   - ctx context.Context
//   - ID uuid.UUID
//   - payload map[string]any
//   - trx *gorm.DB
func (_e *MockIInvestmentRepository_Expecter) UpdateWithMapTx(ctx interface{}, ID interface{}, payload interface{}, trx interface{}) *MockIInvestmentRepository_UpdateWithMapTx_Call {
	return &MockIInvestmentRepository_UpdateWithMapTx_Call{Call: _e.mock.On("UpdateWithMapTx", ctx, ID, payload, trx)}
}

func (_c *MockIInvestmentRepository_UpdateWithMapTx_Call) Run(run func(ctx context.Context, ID uuid.UUID, payload map[string]any, trx *gorm.DB)) *MockIInvestmentRepository_UpdateWithMapTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 map[string]any
		if args[2] != nil {
			arg2 = args[2].(map[string]any)
		}
		var arg3 *gorm.DB
		if args[3] != nil {
			arg3 = args[3].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockIInvestmentRepository_UpdateWithMapTx_Call) Return(investment1 investment.Investment, err error) *MockIInvestmentRepository_UpdateWithMapTx_Call {
	_c.Call.Return(investment1, err)
	return _c
}

func (_c *MockIInvestmentRepository_UpdateWithMapTx_Call) RunAndReturn(run func(ctx context.Context, ID uuid.UUID, payload map[string]any, trx *gorm.DB) (investment.Investment, error)) *MockIInvestmentRepository_UpdateWithMapTx_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateWithTx provides a mock function for the type MockIInvestmentRepository
func (_mock *MockIInvestmentRepository) UpdateWithTx(ctx context.Context, ID uuid.UUID, model investment.Investment, trx *gorm.DB) (investment.Investment, error) {
	ret := _mock.Called(ctx, ID, model, trx)

	if len(ret) == 0 {
		panic("no return value specified for UpdateWithTx")
	}

	var r0 investment.Investment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, investment.Investment, *gorm.DB) (investment.Investment, error)); ok {
		return returnFunc(ctx, ID, model, trx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, investment.Investment, *gorm.DB) investment.Investment); ok {
		r0 = returnFunc(ctx, ID, model, trx)
	} else {
		r0 = ret.Get(0).(investment.Investment)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, investment.Investment, *gorm.DB) error); ok {
		r1 = returnFunc(ctx, ID, model, trx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIInvestmentRepository_UpdateWithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateWithTx'
type MockIInvestmentRepository_UpdateWithTx_Call struct {
	*mock.Call
}

// UpdateWithTx is a helper method to define mock.On call
//   - ctx context.Context
//   - ID uuid.UUID
//   - model investment.Investment
//   - trx *gorm.DB
func (_e *MockIInvestmentRepository_Expecter) UpdateWithTx(ctx interface{}, ID interface{}, model interface{}, trx interface{}) *MockIInvestmentRepository_UpdateWithTx_Call {
	return &MockIInvestmentRepository_UpdateWithTx_Call{Call: _e.mock.On("UpdateWithTx", ctx, ID, model, trx)}
}

func (_c *MockIInvestmentRepository_UpdateWithTx_Call) Run(run func(ctx context.Context, ID uuid.UUID, model investment.Investment, trx *gorm.DB)) *MockIInvestmentRepository_UpdateWithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 investment.Investment
		if args[2] != nil {
			arg2 = args[2].(investment.Investment)
		}
		var arg3 *gorm.DB
		if args[3] != nil {
			arg3 = args[3].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockIInvestmentRepository_UpdateWithTx_Call) Return(investment1 investment.Investment, err error) *MockIInvestmentRepository_UpdateWithTx_Call {
	_c.Call.Return(investment1, err)
	return _c
}

func (_c *MockIInvestmentRepository_UpdateWithTx_Call) RunAndReturn(run func(ctx context.Context, ID uuid.UUID, model investment.Investment, trx *gorm.DB) (investment.Investment, error)) *MockIInvestmentRepository_UpdateWithTx_Call {
	_c.Call.Return(run)
	return _c
}
