// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package bus

import (
	"github.com/BagusAK95/amarta_test/internal/infrastructure/bus"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBus creates a new instance of MockBus. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBus[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBus[T] {
	mock := &MockBus[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBus is an autogenerated mock type for the Bus type
type MockBus[T any] struct {
	mock.Mock
}

type MockBus_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *MockBus[T]) EXPECT() *MockBus_Expecter[T] {
	return &MockBus_Expecter[T]{mock: &_m.Mock}
}

// HasCallback provides a mock function for the type MockBus
func (_mock *MockBus[T]) HasCallback(topic string) bool {
	ret := _mock.Called(topic)

	if len(ret) == 0 {
		panic("no return value specified for HasCallback")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(topic)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockBus_HasCallback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasCallback'
type MockBus_HasCallback_Call[T any] struct {
	*mock.Call
}

// HasCallback is a helper method to define mock.On call
//   - topic string
func (_e *MockBus_Expecter[T]) HasCallback(topic interface{}) *MockBus_HasCallback_Call[T] {
	return &MockBus_HasCallback_Call[T]{Call: _e.mock.On("HasCallback", topic)}
}

func (_c *MockBus_HasCallback_Call[T]) Run(run func(topic string)) *MockBus_HasCallback_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBus_HasCallback_Call[T]) Return(b bool) *MockBus_HasCallback_Call[T] {
	_c.Call.Return(b)
	return _c
}

func (_c *MockBus_HasCallback_Call[T]) RunAndReturn(run func(topic string) bool) *MockBus_HasCallback_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Publish provides a mock function for the type MockBus
func (_mock *MockBus[T]) Publish(topic string, arg T) {
	_mock.Called(topic, arg)
	return
}

// MockBus_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MockBus_Publish_Call[T any] struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - topic string
//   - arg T
func (_e *MockBus_Expecter[T]) Publish(topic interface{}, arg interface{}) *MockBus_Publish_Call[T] {
	return &MockBus_Publish_Call[T]{Call: _e.mock.On("Publish", topic, arg)}
}

func (_c *MockBus_Publish_Call[T]) Run(run func(topic string, arg T)) *MockBus_Publish_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 T
		if args[1] != nil {
			arg1 = args[1].(T)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBus_Publish_Call[T]) Return() *MockBus_Publish_Call[T] {
	_c.Call.Return()
	return _c
}

func (_c *MockBus_Publish_Call[T]) RunAndReturn(run func(topic string, arg T)) *MockBus_Publish_Call[T] {
	_c.Run(run)
	return _c
}

// Subscribe provides a mock function for the type MockBus
func (_mock *MockBus[T]) Subscribe(topic string, fn func(T)) bus.SubscriptionRef {
	ret := _mock.Called(topic, fn)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 bus.SubscriptionRef
	if returnFunc, ok := ret.Get(0).(func(string, func(T)) bus.SubscriptionRef); ok {
		r0 = returnFunc(topic, fn)
	} else {
		r0 = ret.Get(0).(bus.SubscriptionRef)
	}
	return r0
}

// MockBus_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type MockBus_Subscribe_Call[T any] struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - topic string
//   - fn func(T)
func (_e *MockBus_Expecter[T]) Subscribe(topic interface{}, fn interface{}) *MockBus_Subscribe_Call[T] {
	return &MockBus_Subscribe_Call[T]{Call: _e.mock.On("Subscribe", topic, fn)}
}

func (_c *MockBus_Subscribe_Call[T]) Run(run func(topic string, fn func(T))) *MockBus_Subscribe_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 func(T)
		if args[1] != nil {
			arg1 = args[1].(func(T))
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBus_Subscribe_Call[T]) Return(subscriptionRef bus.SubscriptionRef) *MockBus_Subscribe_Call[T] {
	_c.Call.Return(subscriptionRef)
	return _c
}

func (_c *MockBus_Subscribe_Call[T]) RunAndReturn(run func(topic string, fn func(T)) bus.SubscriptionRef) *MockBus_Subscribe_Call[T] {
	_c.Call.Return(run)
	return _c
}

// SubscribeAsync provides a mock function for the type MockBus
func (_mock *MockBus[T]) SubscribeAsync(topic string, fn func(T), transactional bool) bus.SubscriptionRef {
	ret := _mock.Called(topic, fn, transactional)

	if len(ret) == 0 {
		panic("no return value specified for SubscribeAsync")
	}

	var r0 bus.SubscriptionRef
	if returnFunc, ok := ret.Get(0).(func(string, func(T), bool) bus.SubscriptionRef); ok {
		r0 = returnFunc(topic, fn, transactional)
	} else {
		r0 = ret.Get(0).(bus.SubscriptionRef)
	}
	return r0
}

// MockBus_SubscribeAsync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubscribeAsync'
type MockBus_SubscribeAsync_Call[T any] struct {
	*mock.Call
}

// SubscribeAsync is a helper method to define mock.On call
//   - topic string
//   - fn func(T)
//   - transactional bool
func (_e *MockBus_Expecter[T]) SubscribeAsync(topic interface{}, fn interface{}, transactional interface{}) *MockBus_SubscribeAsync_Call[T] {
	return &MockBus_SubscribeAsync_Call[T]{Call: _e.mock.On("SubscribeAsync", topic, fn, transactional)}
}

func (_c *MockBus_SubscribeAsync_Call[T]) Run(run func(topic string, fn func(T), transactional bool)) *MockBus_SubscribeAsync_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 func(T)
		if args[1] != nil {
			arg1 = args[1].(func(T))
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBus_SubscribeAsync_Call[T]) Return(subscriptionRef bus.SubscriptionRef) *MockBus_SubscribeAsync_Call[T] {
	_c.Call.Return(subscriptionRef)
	return _c
}

func (_c *MockBus_SubscribeAsync_Call[T]) RunAndReturn(run func(topic string, fn func(T), transactional bool) bus.SubscriptionRef) *MockBus_SubscribeAsync_Call[T] {
	_c.Call.Return(run)
	return _c
}

// SubscribeOnce provides a mock function for the type MockBus
func (_mock *MockBus[T]) SubscribeOnce(topic string, fn func(T)) bus.SubscriptionRef {
	ret := _mock.Called(topic, fn)

	if len(ret) == 0 {
		panic("no return value specified for SubscribeOnce")
	}

	var r0 bus.SubscriptionRef
	if returnFunc, ok := ret.Get(0).(func(string, func(T)) bus.SubscriptionRef); ok {
		r0 = returnFunc(topic, fn)
	} else {
		r0 = ret.Get(0).(bus.SubscriptionRef)
	}
	return r0
}

// MockBus_SubscribeOnce_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubscribeOnce'
type MockBus_SubscribeOnce_Call[T any] struct {
	*mock.Call
}

// SubscribeOnce is a helper method to define mock.On call
//   - topic string
//   - fn func(T)
func (_e *MockBus_Expecter[T]) SubscribeOnce(topic interface{}, fn interface{}) *MockBus_SubscribeOnce_Call[T] {
	return &MockBus_SubscribeOnce_Call[T]{Call: _e.mock.On("SubscribeOnce", topic, fn)}
}

func (_c *MockBus_SubscribeOnce_Call[T]) Run(run func(topic string, fn func(T))) *MockBus_SubscribeOnce_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 func(T)
		if args[1] != nil {
			arg1 = args[1].(func(T))
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBus_SubscribeOnce_Call[T]) Return(subscriptionRef bus.SubscriptionRef) *MockBus_SubscribeOnce_Call[T] {
	_c.Call.Return(subscriptionRef)
	return _c
}

func (_c *MockBus_SubscribeOnce_Call[T]) RunAndReturn(run func(topic string, fn func(T)) bus.SubscriptionRef) *MockBus_SubscribeOnce_Call[T] {
	_c.Call.Return(run)
	return _c
}

// SubscribeOnceAsync provides a mock function for the type MockBus
func (_mock *MockBus[T]) SubscribeOnceAsync(topic string, fn func(T)) bus.SubscriptionRef {
	ret := _mock.Called(topic, fn)

	if len(ret) == 0 {
		panic("no return value specified for SubscribeOnceAsync")
	}

	var r0 bus.SubscriptionRef
	if returnFunc, ok := ret.Get(0).(func(string, func(T)) bus.SubscriptionRef); ok {
		r0 = returnFunc(topic, fn)
	} else {
		r0 = ret.Get(0).(bus.SubscriptionRef)
	}
	return r0
}

// MockBus_SubscribeOnceAsync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubscribeOnceAsync'
type MockBus_SubscribeOnceAsync_Call[T any] struct {
	*mock.Call
}

// SubscribeOnceAsync is a helper method to define mock.On call
//   - topic string
//   - fn func(T)
func (_e *MockBus_Expecter[T]) SubscribeOnceAsync(topic interface{}, fn interface{}) *MockBus_SubscribeOnceAsync_Call[T] {
	return &MockBus_SubscribeOnceAsync_Call[T]{Call: _e.mock.On("SubscribeOnceAsync", topic, fn)}
}

func (_c *MockBus_SubscribeOnceAsync_Call[T]) Run(run func(topic string, fn func(T))) *MockBus_SubscribeOnceAsync_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 func(T)
		if args[1] != nil {
			arg1 = args[1].(func(T))
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBus_SubscribeOnceAsync_Call[T]) Return(subscriptionRef bus.SubscriptionRef) *MockBus_SubscribeOnceAsync_Call[T] {
	_c.Call.Return(subscriptionRef)
	return _c
}

func (_c *MockBus_SubscribeOnceAsync_Call[T]) RunAndReturn(run func(topic string, fn func(T)) bus.SubscriptionRef) *MockBus_SubscribeOnceAsync_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Unsubscribe provides a mock function for the type MockBus
func (_mock *MockBus[T]) Unsubscribe(topic string, ref bus.SubscriptionRef) {
	_mock.Called(topic, ref)
	return
}

// MockBus_Unsubscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unsubscribe'
type MockBus_Unsubscribe_Call[T any] struct {
	*mock.Call
}

// Unsubscribe is a helper method to define mock.On call
//   - topic string
//   - ref bus.SubscriptionRef
func (_e *MockBus_Expecter[T]) Unsubscribe(topic interface{}, ref interface{}) *MockBus_Unsubscribe_Call[T] {
	return &MockBus_Unsubscribe_Call[T]{Call: _e.mock.On("Unsubscribe", topic, ref)}
}

func (_c *MockBus_Unsubscribe_Call[T]) Run(run func(topic string, ref bus.SubscriptionRef)) *MockBus_Unsubscribe_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 bus.SubscriptionRef
		if args[1] != nil {
			arg1 = args[1].(bus.SubscriptionRef)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBus_Unsubscribe_Call[T]) Return() *MockBus_Unsubscribe_Call[T] {
	_c.Call.Return()
	return _c
}

func (_c *MockBus_Unsubscribe_Call[T]) RunAndReturn(run func(topic string, ref bus.SubscriptionRef)) *MockBus_Unsubscribe_Call[T] {
	_c.Run(run)
	return _c
}

// WaitAsync provides a mock function for the type MockBus
func (_mock *MockBus[T]) WaitAsync() {
	_mock.Called()
	return
}

// MockBus_WaitAsync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WaitAsync'
type MockBus_WaitAsync_Call[T any] struct {
	*mock.Call
}

// WaitAsync is a helper method to define mock.On call
func (_e *MockBus_Expecter[T]) WaitAsync() *MockBus_WaitAsync_Call[T] {
	return &MockBus_WaitAsync_Call[T]{Call: _e.mock.On("WaitAsync")}
}

func (_c *MockBus_WaitAsync_Call[T]) Run(run func()) *MockBus_WaitAsync_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBus_WaitAsync_Call[T]) Return() *MockBus_WaitAsync_Call[T] {
	_c.Call.Return()
	return _c
}

func (_c *MockBus_WaitAsync_Call[T]) RunAndReturn(run func()) *MockBus_WaitAsync_Call[T] {
	_c.Run(run)
	return _c
}
