// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package bus

import (
	"github.com/BagusAK95/amarta_test/internal/infrastructure/bus"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBusSubscriber creates a new instance of MockBusSubscriber. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBusSubscriber[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBusSubscriber[T] {
	mock := &MockBusSubscriber[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBusSubscriber is an autogenerated mock type for the BusSubscriber type
type MockBusSubscriber[T any] struct {
	mock.Mock
}

type MockBusSubscriber_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *MockBusSubscriber[T]) EXPECT() *MockBusSubscriber_Expecter[T] {
	return &MockBusSubscriber_Expecter[T]{mock: &_m.Mock}
}

// Subscribe provides a mock function for the type MockBusSubscriber
func (_mock *MockBusSubscriber[T]) Subscribe(topic string, fn func(T)) bus.SubscriptionRef {
	ret := _mock.Called(topic, fn)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 bus.SubscriptionRef
	if returnFunc, ok := ret.Get(0).(func(string, func(T)) bus.SubscriptionRef); ok {
		r0 = returnFunc(topic, fn)
	} else {
		r0 = ret.Get(0).(bus.SubscriptionRef)
	}
	return r0
}

// MockBusSubscriber_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type MockBusSubscriber_Subscribe_Call[T any] struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - topic string
//   - fn func(T)
func (_e *MockBusSubscriber_Expecter[T]) Subscribe(topic interface{}, fn interface{}) *MockBusSubscriber_Subscribe_Call[T] {
	return &MockBusSubscriber_Subscribe_Call[T]{Call: _e.mock.On("Subscribe", topic, fn)}
}

func (_c *MockBusSubscriber_Subscribe_Call[T]) Run(run func(topic string, fn func(T))) *MockBusSubscriber_Subscribe_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 func(T)
		if args[1] != nil {
			arg1 = args[1].(func(T))
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBusSubscriber_Subscribe_Call[T]) Return(subscriptionRef bus.SubscriptionRef) *MockBusSubscriber_Subscribe_Call[T] {
	_c.Call.Return(subscriptionRef)
	return _c
}

func (_c *MockBusSubscriber_Subscribe_Call[T]) RunAndReturn(run func(topic string, fn func(T)) bus.SubscriptionRef) *MockBusSubscriber_Subscribe_Call[T] {
	_c.Call.Return(run)
	return _c
}

// SubscribeAsync provides a mock function for the type MockBusSubscriber
func (_mock *MockBusSubscriber[T]) SubscribeAsync(topic string, fn func(T), transactional bool) bus.SubscriptionRef {
	ret := _mock.Called(topic, fn, transactional)

	if len(ret) == 0 {
		panic("no return value specified for SubscribeAsync")
	}

	var r0 bus.SubscriptionRef
	if returnFunc, ok := ret.Get(0).(func(string, func(T), bool) bus.SubscriptionRef); ok {
		r0 = returnFunc(topic, fn, transactional)
	} else {
		r0 = ret.Get(0).(bus.SubscriptionRef)
	}
	return r0
}

// MockBusSubscriber_SubscribeAsync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubscribeAsync'
type MockBusSubscriber_SubscribeAsync_Call[T any] struct {
	*mock.Call
}

// SubscribeAsync is a helper method to define mock.On call
//   - topic string
//   - fn func(T)
//   - transactional bool
func (_e *MockBusSubscriber_Expecter[T]) SubscribeAsync(topic interface{}, fn interface{}, transactional interface{}) *MockBusSubscriber_SubscribeAsync_Call[T] {
	return &MockBusSubscriber_SubscribeAsync_Call[T]{Call: _e.mock.On("SubscribeAsync", topic, fn, transactional)}
}

func (_c *MockBusSubscriber_SubscribeAsync_Call[T]) Run(run func(topic string, fn func(T), transactional bool)) *MockBusSubscriber_SubscribeAsync_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 func(T)
		if args[1] != nil {
			arg1 = args[1].(func(T))
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBusSubscriber_SubscribeAsync_Call[T]) Return(subscriptionRef bus.SubscriptionRef) *MockBusSubscriber_SubscribeAsync_Call[T] {
	_c.Call.Return(subscriptionRef)
	return _c
}

func (_c *MockBusSubscriber_SubscribeAsync_Call[T]) RunAndReturn(run func(topic string, fn func(T), transactional bool) bus.SubscriptionRef) *MockBusSubscriber_SubscribeAsync_Call[T] {
	_c.Call.Return(run)
	return _c
}

// SubscribeOnce provides a mock function for the type MockBusSubscriber
func (_mock *MockBusSubscriber[T]) SubscribeOnce(topic string, fn func(T)) bus.SubscriptionRef {
	ret := _mock.Called(topic, fn)

	if len(ret) == 0 {
		panic("no return value specified for SubscribeOnce")
	}

	var r0 bus.SubscriptionRef
	if returnFunc, ok := ret.Get(0).(func(string, func(T)) bus.SubscriptionRef); ok {
		r0 = returnFunc(topic, fn)
	} else {
		r0 = ret.Get(0).(bus.SubscriptionRef)
	}
	return r0
}

// MockBusSubscriber_SubscribeOnce_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubscribeOnce'
type MockBusSubscriber_SubscribeOnce_Call[T any] struct {
	*mock.Call
}

// SubscribeOnce is a helper method to define mock.On call
//   - topic string
//   - fn func(T)
func (_e *MockBusSubscriber_Expecter[T]) SubscribeOnce(topic interface{}, fn interface{}) *MockBusSubscriber_SubscribeOnce_Call[T] {
	return &MockBusSubscriber_SubscribeOnce_Call[T]{Call: _e.mock.On("SubscribeOnce", topic, fn)}
}

func (_c *MockBusSubscriber_SubscribeOnce_Call[T]) Run(run func(topic string, fn func(T))) *MockBusSubscriber_SubscribeOnce_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 func(T)
		if args[1] != nil {
			arg1 = args[1].(func(T))
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBusSubscriber_SubscribeOnce_Call[T]) Return(subscriptionRef bus.SubscriptionRef) *MockBusSubscriber_SubscribeOnce_Call[T] {
	_c.Call.Return(subscriptionRef)
	return _c
}

func (_c *MockBusSubscriber_SubscribeOnce_Call[T]) RunAndReturn(run func(topic string, fn func(T)) bus.SubscriptionRef) *MockBusSubscriber_SubscribeOnce_Call[T] {
	_c.Call.Return(run)
	return _c
}

// SubscribeOnceAsync provides a mock function for the type MockBusSubscriber
func (_mock *MockBusSubscriber[T]) SubscribeOnceAsync(topic string, fn func(T)) bus.SubscriptionRef {
	ret := _mock.Called(topic, fn)

	if len(ret) == 0 {
		panic("no return value specified for SubscribeOnceAsync")
	}

	var r0 bus.SubscriptionRef
	if returnFunc, ok := ret.Get(0).(func(string, func(T)) bus.SubscriptionRef); ok {
		r0 = returnFunc(topic, fn)
	} else {
		r0 = ret.Get(0).(bus.SubscriptionRef)
	}
	return r0
}

// MockBusSubscriber_SubscribeOnceAsync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubscribeOnceAsync'
type MockBusSubscriber_SubscribeOnceAsync_Call[T any] struct {
	*mock.Call
}

// SubscribeOnceAsync is a helper method to define mock.On call
//   - topic string
//   - fn func(T)
func (_e *MockBusSubscriber_Expecter[T]) SubscribeOnceAsync(topic interface{}, fn interface{}) *MockBusSubscriber_SubscribeOnceAsync_Call[T] {
	return &MockBusSubscriber_SubscribeOnceAsync_Call[T]{Call: _e.mock.On("SubscribeOnceAsync", topic, fn)}
}

func (_c *MockBusSubscriber_SubscribeOnceAsync_Call[T]) Run(run func(topic string, fn func(T))) *MockBusSubscriber_SubscribeOnceAsync_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 func(T)
		if args[1] != nil {
			arg1 = args[1].(func(T))
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBusSubscriber_SubscribeOnceAsync_Call[T]) Return(subscriptionRef bus.SubscriptionRef) *MockBusSubscriber_SubscribeOnceAsync_Call[T] {
	_c.Call.Return(subscriptionRef)
	return _c
}

func (_c *MockBusSubscriber_SubscribeOnceAsync_Call[T]) RunAndReturn(run func(topic string, fn func(T)) bus.SubscriptionRef) *MockBusSubscriber_SubscribeOnceAsync_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Unsubscribe provides a mock function for the type MockBusSubscriber
func (_mock *MockBusSubscriber[T]) Unsubscribe(topic string, ref bus.SubscriptionRef) {
	_mock.Called(topic, ref)
	return
}

// MockBusSubscriber_Unsubscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unsubscribe'
type MockBusSubscriber_Unsubscribe_Call[T any] struct {
	*mock.Call
}

// Unsubscribe is a helper method to define mock.On call
//   - topic string
//   - ref bus.SubscriptionRef
func (_e *MockBusSubscriber_Expecter[T]) Unsubscribe(topic interface{}, ref interface{}) *MockBusSubscriber_Unsubscribe_Call[T] {
	return &MockBusSubscriber_Unsubscribe_Call[T]{Call: _e.mock.On("Unsubscribe", topic, ref)}
}

func (_c *MockBusSubscriber_Unsubscribe_Call[T]) Run(run func(topic string, ref bus.SubscriptionRef)) *MockBusSubscriber_Unsubscribe_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 bus.SubscriptionRef
		if args[1] != nil {
			arg1 = args[1].(bus.SubscriptionRef)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBusSubscriber_Unsubscribe_Call[T]) Return() *MockBusSubscriber_Unsubscribe_Call[T] {
	_c.Call.Return()
	return _c
}

func (_c *MockBusSubscriber_Unsubscribe_Call[T]) RunAndReturn(run func(topic string, ref bus.SubscriptionRef)) *MockBusSubscriber_Unsubscribe_Call[T] {
	_c.Run(run)
	return _c
}
